### ISSUE TITLE
Android CSV display

### ISSUE THREAD

**Issue by duggalsu** [CollaboraOnline/online#1137]
**Describe the bug**
A CSV file opens successfully but the entire comma-separated row is displayed in a single cell instead of being split across cells based on the delimiter.

**Additional context**
This is using the Collabora Office from the official F-Droid repository.

**Comment by mrkara** [comment]
Hi @duggalsu,

Thank you for reporting the issue! Could you please provide a sample file for reproducing/testing the issue?

**Comment by rb-338** [comment]
I suspect the issue is CSV files opening in Writer instead of Calc - confusing as the icon for the CSV file is a spreadsheet one.
I've installed Collabora Office (6.4.3 from F-Droid) on a Chromebook (HP 14db0500sa) and see no way of opening a CSV file in Calc. A possible workaround, from within Calc, of inserting a sheet from a file location (the desired CSV file) does not seem available either.

**Comment by Ezinnem** [comment]
The CSV file can be opened using the Collabora Office version 6.4.13 (git hash: [255f42ff](https://github.com/CollaboraOnline/online/commits/255f42ff)).

@duggalsu, you can update your Collabora office app version and test again.
