### ISSUE TITLE
Support mentioning of contacts in comments

### ISSUE THREAD

**Issue by thkoch2001** [CollaboraOnline/online#1529]
**Is your feature request related to a problem? Please describe.**
I asked in Nextcloud for Google Docs-like features of mentioning users in comments:
https://github.com/nextcloud/richdocuments/issues/1380

This feature request is for CollaboraOnline to provide the necessary APIs.

**Describe the solution you'd like**

When a certain symbol gets entered in a comment, e.g. "+" or "@", CollaboraOnline offers an autocomplete of usernames. CO needs to call into the hosting application to get the list of autocompletions.

Once the comment gets posted, CO instructs the hosting application to notify a set of users about the new comment.

**Comment by thkoch2001** [comment]
I believe issue #1673 is related to this one.
I want automatic sharing of comments with mentioned users. #1673 is about getting a link that can be shared manually.

**Comment by juliushaertl** [comment]
After discussing this with @kendy we'd need to have an implementation of this in core first to properly persist the mentions among with the user metadata within the document files

Requirements for a "Mention" element that users would add through the UI:
- Unique user identifier (could be any string, for Nextcloud it would be either the user id or federated cloud id)
- Display name (readable name of the user, as the user id might be a uuid or anything that would not be user friendly)
- E-Mail address (Optional, but could help for providing an option to interact with the user through Collabora Office on the desktop)
- Avatar (Similar to https://github.com/CollaboraOnline/online/issues/4590 in order to be able to display the avatar of the mentioned user)

To give a more concrete example, integrating with a Nextcloud instance on cloud.example.com  if a user would type `@Julius` the interface would fetch the user metadata from Nextcloud and persist that to the file:
- userId: julius@cloud.example.com
- displayName: Julius Haertl
- email: julius@example.com
- avatar: base64 encoded avatar

One additional thing to consider would be that depending on the integrator the userid might not work as a cross reference, between different integrators, for that it would be required to have some way to differentiate:

- namespace with a prefix `nextcloud:julius@cloud.example.com`
- use a url, so that the integrator can check if it is for example a nextcloud instance, this could use the Nextcloud profile page https://cloud.example.com/u/julius
- add an additional metadata for the integrator identifier

Open questions:
- Can this be supported on only specific types (like OpenDocument) or also others like OOXML?

Leaving this up to @kendy for further evaluation of the technical details on the core/cool side as discussed.

**Comment by juliushaertl** [comment]
First parts were already done for in document mentions which is waiting for the next major Nextcloud release. Mentions in comments are still up for discussion though.

**Comment by juliushaertl** [comment]
Yes

**Comment by Hoeze** [comment]
NC26 was released in July, what is the state of this issue today?

**Comment by dorkmaneuver** [comment]
+1, I think this is a very useful collaborative feature and users often stress that this is better in Google docs... can we put this forward also with Collabora?

**Comment by botsarenthuman** [comment]
A user also asked about this today, specifically related to mail-merge and Nextcloud
