### ISSUE TITLE
Different highlight color in highlight color icon of sidebar and toolbar

### ISSUE THREAD

**Issue by rparth07** [CollaboraOnline/online#1577]
**Describe the bug**
If we change highlight color from toolbar , the highlight color icon in sidebar does not change, but reverse is possible means if we change highlight color from sidebar then highlight color in toolbar icon does change.

**To Reproduce**
         1. Change highlight color from toolbar and notice that highlight color of sidebar will not change 

**Expected behavior**
It should change the highlight color icon of sidebar when changing the highlight color from toolbar
     

**Actual behavior**
If we change the highlight color icon from toolbar then the highlight color icon in sidebar does not change.

**Screenshots**
![bug1](https://user-images.githubusercontent.com/58837400/109817264-baa05200-7c57-11eb-8602-50898ceb250f.png)

**Desktop (please complete the following information)**
 - OS: Windows 10 
 - Browser: Firefox

**Comment by thebearon** [comment]
Indeed, confirmed with version 6.4.7.

**Comment by ayhanyalcinsoy** [comment]
I would like to trying fix this issue but I couldn't found sidebar source code in COOL

**Comment by kcmaxwell** [comment]
I've found where the problem occurs, in the _sendColorCommand function in browser/src/control/Control.JSDialogBuilder.js.

The problem is here:
`// update the item state as we send`
`var items = builder.map['stateChangeHandler'];`
`items.setItemValue(data.command, builder.parseHexColor(color));`

setItemValue does not trigger a commandstatechanged event, so the colors are not updated at this step.
They only update later, when the uno command completes, and that sends the commandstatechanged event. This is why it only happens on the highlight color, since highlighting waits for user input before completing.
It also sends a number with parseHexColor, when it should be passing a string.

I'd like to fix this, but I'd like to know if there are any other ways to trigger the commandstatechanged event.
I can use builder.map.fire to fire the event in sendColorCommand and that will fix it, but do we want the setItemValue function to also trigger commandstatechanged events? And if so, how would we trigger those events?

@pedropintosilva If you have any ideas, or can ping someone else who knows this, let me know please.

**Comment by timur-g** [comment]
This seem to work in 23.05. Please retest.
