### ISSUE TITLE
iOS App: Calc: It is not possible to delete a created chart (diagram) through the "long press menu"

### ISSUE THREAD

**Issue by Gianni154** [CollaboraOnline/online#1751]
**Describe the bug**
In spreadsheet document it is not possible to delete a created chart through the "long press menu". It is only possible to cut it out.

**To Reproduce**

1. Open the Collabora iOS App
2. Open a new or an existing spreadsheet (calc)
3. Go to Edit Mode and select "Insert" in the notebookbar
4. Select "Charts Wizard" to create a chart
5. Press on the created diagram until the Long-Press Menu appears. No Delete option is displayed.

**Expected behavior**
It is possible to delete the created diagram. The Delete option is available in the long press menu.

**Actual behavior**
It is not possible to delete the created diagram. Delete option is not present in the long press menu. 

**Screenshots**

![File_000](https://user-images.githubusercontent.com/78140364/111472084-ec221e80-8729-11eb-9f40-7364481a98a9.jpeg)

**Device**
 - Device: iPad 6th generation 
 - OS: iPad OS 14.4
 - Version: iOS Collabora App Version 6.4.6 (1)

**Comment by thebearon** [comment]
Technically, cutting the chart has the same effect (except it'd be added to the clipboard in that case, too), but indeed, a separate Delete option would be reasonable on a device where there's normally no Delete button to press.

Since normally the desktop menu is shown, and adding the item on desktop would be unadvised, I wonder if it could be added only for mobile devices. In fact, I can see phones already have a Delete item for charts. @eszkadev, can you share how that is handled, and if there'd be a simple way to have that on tablets as well?
