### ISSUE TITLE
Cleanup HTTP header writing duplication

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#207]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @mmeeks @kendy 

We have a -lot- of code that duplicates HTTP header writing.

Take this chunk:

wsd/LOOLWSD.cpp-                    std::ostringstream oss;
wsd/LOOLWSD.cpp:                    oss << "HTTP/1.1 401 \r\n"
wsd/LOOLWSD.cpp-                        << "Content-Type: text/html charset=UTF-8\r\n"
wsd/LOOLWSD.cpp-                        << "Date: " << Poco::DateTimeFormatter::format(Poco::Timestamp(), Poco::DateTimeFormat::HTTP_FORMAT) << "\r\n"
wsd/LOOLWSD.cpp-                        << "User-Agent: " << WOPI_AGENT_STRING << "\r\n"
wsd/LOOLWSD.cpp-                        << "WWW-authenticate: Basic realm=\"online\"\r\n"
wsd/LOOLWSD.cpp-                        << "\r\n";

This is not using eg. "Date: " << Util::getHttpTimeNow() << "\r\n"

As many other instances do (oddly) - so perhaps a 1st patch to use the getHttpTimeNow() wherever it is not would be helpful.

After that we should really have a method that sends a nicely formed error message for all the error cases, that we can pass a number into, and perhaps some custom extra headers too - a little bit of API design - and then clean all of this up.

I'd expect the socket->send() to happen and an optional socket->shutdown() too - to simplify this left and right.

Thanks ! =)

**Comment by kendy** [comment]
git grep 'Date:.*DateTimeFormatter'

to find the places that use the above; and then 

git grep 'HTTP/1\.1 [^12]'

the places where we send an error message :-)

**Comment by kendy** [comment]
There are still other places, reopening.

**Comment by Dagefoerde** [comment]
`git grep 'HTTP/1.1 [^12]'` <- I found that one interesting, thanks @kendy!

So there is `FileServerRequestHandler::sendError` (https://github.com/CollaboraOnline/online/blob/29251ef432b0cd531b408c8658aafa590510c47b/wsd/FileServer.cpp#L492) which pretty much seems to do what @mmeeks is trying to achieve, right? Yet I fear that

a) `FileServerRequestHandler` shouldn't be the class handling all kinds of errors, because not all errors relate to FileServerRequests, and
b) some parts of that method could be "too much" for most of the errors (specifically: a very verbose error method -- which is cool as an optional feature, but most of the other error states are not providing much of a message)

To proceed, we could have a more generic `sendError` method in some place in the codebase that outputs error headers and bodies. It would accept an HTTP status, additional headers, and a body. Then I would rewrite `FileServerRequestHandler::sendError` to use that generic method, and rewrite the other instances of `git grep 'HTTP/1.1 [^12]'` as well.

Does that sound reasonable? Where would be a good place to put a generic `sendError` method, `common/Util.cpp`? First time in your codebase, so any advice is appreciated :+1:
