### ISSUE TITLE
Notebookbar Tooltip show tab name

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2171]
when you hover at a command with label, there is a tooltip which show the tab name.

![photo5780697110931420580](https://user-images.githubusercontent.com/8517736/116196529-eb6ea600-a733-11eb-9e83-28df239ea28e.jpg)

If there is a label already for the command, no tooltip is needed.

**Comment by pedropintosilva** [comment]
This is a regression and unfortunately it's a regression that also found it's way to stable branch.
Tested with an old version https://github.com/CollaboraOnline/online/commits/7affc26 and it's fine there

**Comment by pedropintosilva** [comment]
I couldn't for the live of me fix this. I think  the say tooltips are handled have changed. What I tried:

- I thought I could simple do something like
  ```js
  $(div).tooltip({disabled: true});
  ```
  or
  ```js
  $(button).tooltip({disabled: true});
  ```
  within `Control.JSDialogBuilder.js:__unoToolButton` to disabled buttons that have labels
  - but didn't seem to affect tooltips at all
- As a test commenting all
  ```js
  builder.map.uiManager.enableTooltip(div);
  ```
instances from `Control.JSDialogBuilder.js` and `builder.map.uiManager.enableTooltip(container);` from `Control.NotebookbarBuilder.js` had not affect (tooltips keep showing up)
- And finally I think this is not handled by `UIManager` because commenting `enableTooltip` contents had no change:
  ```js
	enableTooltip: function(element) {
		var elem = $(element);
		if (window.mode.isDesktop()) {
			// elem.tooltip();
			// elem.click(function() {
			// 	$('.ui-tooltip').fadeOut(function() {
			// 		$(this).remove();
			// 	});
			// });
		}
  ```
