### ISSUE TITLE
Sidebar button: should we add a label?

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2295]
@Andreas-Kainz 's idea, feel free to edit this
> The reason for the Issue is, that it's easy to oversee this icons. If you compare it with gdoc's and LibreOffice the sidebar icons are bigger than other icons and they are arranged right to the document. In COOL they are arranged at the tab header where they are not that easy to recognize that they are for show/hide the sidebar.

![image](https://user-images.githubusercontent.com/65948705/117424471-1ae69500-af22-11eb-8db7-a51ec5cc6cdd.png)

**Comment by pedropintosilva** [comment]
Document to add mockups/screenshots or notes https://staging.eu.collaboraonline.com/nextcloud/index.php/s/kEsPSTQwFkonM88

**Comment by Andreas-Kainz** [comment]
The reason for the Issue is, that it's easy to oversee this icons. If you compare it with gdoc's and LibreOffice the sidebar icons are bigger than other icons and they are arranged right to the document. In COOL they are arranged at the tab header where they are not that easy to recognize that they are for show/hide the sidebar.

![photo5811910562416801238](https://user-images.githubusercontent.com/8517736/117423705-4cab2c00-af21-11eb-847c-cd419417eec4.jpg)

**Comment by Andreas-Kainz** [comment]
I will add sidebar visible commands to layout tab.
