### ISSUE TITLE
Notebookbar File Tab: Add NC commands

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2314]
If you use COOl with NC integration there will be Share and See history visible, which show the NC sidebar. I suggest to add all the 5 commands from NC sidebar and add them to a separate Section at the File tab.

![FileTab](https://user-images.githubusercontent.com/8517736/117636310-f805ec00-b180-11eb-9cbb-575a1ccfd4e4.png)

**Comment by Andreas-Kainz** [comment]
@pedropintosilva feedback? otherwise I will close the issue.

**Comment by pedropintosilva** [comment]
Unfortunately it's not possible to to incorporate NC own icons/action into the notebookbar plus I don't think that would be advisable, what would happen with other integrators? would be really hard.

**Comment by Andreas-Kainz** [comment]
I didn't talk about the icons, I talk about add Activitiy, Chat, Comments commands like Sharing and Versions already is.

**Comment by pedropintosilva** [comment]
yes I understood it but for example  Chat and Comments are not really related to the document (or like from the document) they are NC chat and comments from multiple users when viewing it there and we really do not have at the moment that "bridge".

Nevertheless, you made me think twice about it. Because maybe we can have a condition as we have for share and it it's available display item that does nothing more than being a link (passing url to outside of iframe, to NC saying please open that tab in the NC sidebar)

I thinks this deserves some thought and maybe some input from maybe @kendy (?)

**Comment by Andreas-Kainz** [comment]
I don't think that's that important at least with the better NC integration.
