### ISSUE TITLE
could not preview .pages file

### ISSUE THREAD

**Issue by hyzgh** [CollaboraOnline/online#2459]
**Describe the bug**
Unable to read .pages files. I try to open it, but it only shows blank. While it works well for .docx files.

**To Reproduce**
1. `docker run -t -d -p 9980:9980 -e "domain=" -e "username=admin" -e "password=S3cRet" -e "extra_params=--o:ssl.enable=false" --restart always collabora/code:6.4.8.4`
2. implement WOPI host.
3. open a .pages file, it shows blank. While I could open it well with my local software, so it seems not a problem caused by file.
4. open a .docx file, it looks well.

**Expected behavior**
Expect could preview .pages file normally.

**Actual behavior**
It shows only blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/31174102/119480446-440d7f00-bd84-11eb-80f5-7670e92863ae.png)

![image](https://user-images.githubusercontent.com/31174102/119480364-293b0a80-bd84-11eb-9f56-f53bb4faf526.png)

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: chrome
 - Version: 6.4.8.4

**Additional context**

**Comment by Ezinnem** [comment]
Please, can you check if the .pages file renders well in the latest LibreOffice version?

If it does not, since both software relies on the "etonyek" library from the Document Liberation Project, it would be helpful that you file a bug report with a sample document attached; using the link below:

https://bugs.documentfoundation.org/enter_bug.cgi?product=Document%20Liberation%20Project
