### ISSUE TITLE
CODE 6.4.10 Calc Regressions: Focus Not in Comment Field When Adding Comment And Comment Popup Sometimes Suddenly Disappears

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2746]
**Describe the bug**

When adding a cell comment in Calc, the focus is not moved to the comment text input field, so you have to explicitly click it to add a comment.

Sometimes, the focus seems to be set to the underlying cell, causing the user to overwrite the actual cell contents. :-( In other cases, the keyboard focus is somewhere else, so typing does not do anything.

Also, the comment popup sometimes spontaneously disappears / auto-closes again - an issue which existed in the past, but which also had been fixed in more recent CODE releases.

There had been quite a few comment related bugs in the past, but it worked much better in recent versions. Unfortunately, it now regressed. Maybe you should add basic comment editing to your default regression test steps before publishing a new version...

**Desktop (please complete the following information)**

OS: Ubuntu 20.04 (KDE neon)
Browser: Chromium
Version: 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

Collabora Online Development Edition (CODE)
Diese Version von Collabora Online Development Edition (CODE) wird bereitgestellt von

LOOLWSD
6.4.10 (git hash: 51b8716)
Angeboten von: ee7c0e28
LOKit
Collabora Office 6.4-42 (git hash: 8aa76ce)
"Ubuntu 18.04.5 LTS"
Copyright © 2021, Collabora Productivity Limited.

**Comment by rpear** [comment]
I can confirm that New Comment focus is sometimes the underlying cell and you can overwrite the cells content. This is using 6.4.10snapshot (git hash: 545ed4a) (Commits on Jul 2, 2021) on a Chromebook web browser.

Comments has more problems:
-Sometimes when typing into the new Comment box it disappears whilst you are typing as if you clicked OK and the remaining text overwrites the cell, with loss of data.
-This one may be by design: Sometimes Comments boxes appear and stick in the same place on the screen - even when scrolling the spreadsheet up and down behind them. To reproduce: Hover mouse over the Comment so that it pops up, move mouse off the Comments top, bottom or right side the comment sticks, you can now scroll document underneath it.   If you move your mouse off the Comment to the left it disappears.
-If you scroll down several rows, click the Comment button, the dialogue partially appears.  i.e. it appears on row 1 even if that is scrolled up out of view, and if you scroll up to the top, you still can't see it all.
-If playing around with the 2 above you end up not being able to get the Comment box to appear again, re-opening the tab fixes it.
-Sometimes - whilst playing around with the above the spreadsheet would take a long time to open up. Perhaps the server was busy with other users, so unrelated, I do not know.

**Comment by thebearon** [comment]
Confirmed, thanks for the feedback, @gohrner, this is a regression in 6.4.10!

@rpear, I'm not sure if all of those items are related to the regression, let's wait until it's fixed, and retest those afterwards, whatever's remaing should be filed separately.

**Comment by Ezinnem** [comment]
The regression regarding the New comment focus has been fixed.

Works fine on LOOLWSD 6.4.10snapshot (git hash: [788e0aa](https://github.com/CollaboraOnline/online/commits/788e0aa)).
