### ISSUE TITLE
CODE 6.4.10 Calc: Select Font Color: Recently Selected Colors Are Not Remembered

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2748]
**Describe the bug**
Normally, the recently selected colours should be remembered in the squares on the bottom right of the popup, shouldn't they? This does not seem to work:
![image](https://user-images.githubusercontent.com/26199042/124350257-e62a4d80-dbf3-11eb-9a71-a57353212b03.png)

Desktop (please complete the following information)

OS: Ubuntu 20.04 (KDE neon)
Browser: Chromium
Version: 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

Collabora Online Development Edition (CODE)
Diese Version von Collabora Online Development Edition (CODE) wird bereitgestellt von

LOOLWSD
6.4.10 (git hash: 51b8716)
Angeboten von: ee7c0e28
LOKit
Collabora Office 6.4-42 (git hash: 8aa76ce)
"Ubuntu 18.04.5 LTS"
Copyright © 2021, Collabora Productivity Limited.

**Comment by rpear** [comment]
I confirm this. It appears that the button is one single button instead of a split button where the left side would just apply the colour to the selected cell/s and the right side with the arrow would show the dropdown to allow you to change the colour.  It still works so not a major, just not behaving as expected. This was using 6.4.10snapshot (git hash: 545ed4a) (Commits on Jul 2, 2021) on a Chromebook web browser.

**Comment by Ezinnem** [comment]
I can confirm the issue 6.4.10 snapshot (git hash: [94a1a06](https://github.com/CollaboraOnline/online/commits/94a1a06)).

**Comment by Ezinnem** [comment]
The issue has been fixed in #3006
