### ISSUE TITLE
Writer document does not save when using a new sytem wide template

### ISSUE THREAD

**Issue by AngelMatilla** [CollaboraOnline/online#3018]
**Describe the bug**
I’m using collabora online cp-6.4.10-6 on Nextcloud 21.0.3. 
I’ve created a new template (.ott) using custom fonts with Libreoffice 7.1.4.2 locally and I’ve uploaded via NextCloud to be used as a system wide template. I’ve also made sure to install the custom fonts in the server. When I create a new file using the NextCloud interface and select the template I can edit the document normally but it does not automatically save. It also does not save when I click the save button. I can however save as another document and then it behaves as it should. 

**To Reproduce**
0. Install google fonts in collabora (working)
1. Create a new template (.ott) using custom font for title, headings, etc (Montserrat) with Libreoffice 7.1.4.2 locally
2. On Nextcloud fo to settings and upload the template as global template
3. On Nextcloud files, create a new doc (the pop-up with templates appears normally)
4. The document is created and is editable, however anything written in the document is not saved and the save button does not work either
5. Saving as another document does the trick and allows to save the document based on the template and it also autosaves normally

**Expected behavior**
The created document based on a template is savable and it autosaves as well.

**Actual behavior**
The created document based on a template does not allow to save and also does not autosave.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Chromium
 - Version: Version 92.0.4515.107 (Official Build) snap (64-bit)

**Comment by rpear** [comment]
Hi, did this work for you before on this setup, or is it the first time you have tried?

**Comment by AngelMatilla** [comment]
It is the first time I've tried in this setup

**Comment by joergmschulz** [comment]
Same here. It seems the same that's been discussed here: https://github.com/nextcloud/richdocuments/issues/1563 . The issue persists for a long time already, unresolved yet.the last known working configuration is NC 20.0.9 and richdocuments 3.7.19.  I'm out of luck finding any hints in any log files (nextcloud log, lool log, browser console). BUT what I have seen: If you unzip the document created with such a template, it does not contain a valid filetype: 

the file mimetype says application/vnd.oasis.opendocument.text-template instead of text.

**Comment by joergmschulz** [comment]
What I didn't test - idea from your hint: Would it work with template  documents created with older versions of LO?

**Comment by AngelMatilla** [comment]
> What I didn't test - idea from your hint: Would it work with template documents created with older versions of LO?

Let me know whether it works in case you try it. This issue is quite hindering for us and shifts back the option to use it in a production environment

**Comment by joergmschulz** [comment]
sure. Please keep an eye on this bug and the referenced bug above. As soon as new info is available, it will show up here and there. And, consider investigating yourself. Maybe, if your environment is a commercial one, you can use your nextcloud subscription to investigate. I don't do this stuff commercially, so I don't have access to the commercial help and funding.

**Comment by AngelMatilla** [comment]
Thanks @joergmschulz I'll keep an eye on both bugs and I'll try to find the time to also investigate. 
Btw, I see you make a reference to Richdocuments. Is that the same as cp-6.4.10-6? I have installed Collabora online using a docker container: https://markus-blog.de/index.php/2018/05/22/how-to-deploy-collabora-online-office-with-docker-in-plesk-and-connect-to-nextcloud/

**Comment by joergmschulz** [comment]
well --- it doesn't make a difference whether you use cp-6.4.10-6 or -8 or any other 6.4 variant. It doesn't even work with libreoffice-master from 10 months ago. My impression is that the real culprit is the richdocuments app of nextcloud. But I didn't find an old enough where everything works alright. This would be a 3.8 version on a NC19 - I don't have any NC19 any longer. If you have time to investigate, you should install a NC19 with some richdocuments app in the 3.x line and update until it doesn't work any longer.

**Comment by thebearon** [comment]
This is a regression in NC richdocuments, let's keep tracking it in https://github.com/nextcloud/richdocuments/issues/1563.
