### ISSUE TITLE
Well this is embarassing... in V 6.4.10-9

### ISSUE THREAD

**Issue by noci2012** [CollaboraOnline/online#3065]
**Describe the bug**
After clicking on a nextcloud document the document doesn;'t show.
After a while there is the message: "Well this is embarassing.... ".
Indeed it is.

**To Reproduce**
1. Go to 'any LibreOffice document in Nextcloud 21.0.3, up to date with apps/modules'
2. Click on 'Document'
3. Scroll down to 'wait for timeout'

**Expected behavior**
A document ready to edit...

**Actual behavior**
There are some error messages:
```
Aug 11 18:13:03 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:03.716217 [ docbroker_001 ] WRN  Waking up dead poll thread [HttpSynReqPoll], started: false, finished: false| ./net/Socket.hpp:680
**Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741075 [ docbroker_001 ] WRN  Socket #29 has timed out while requesting [GET nc.example.net/index.php/apps/richdocuments/wopi/files/1937931_ocuinqirkrns?access_token=NY9WRZZjwd8B6JtwntrWNbSCsD2ZPkZb&access_token_ttl=0&permission=edit] after 30030ms| net/HttpRequest.hpp:1294**
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741190 [ docbroker_001 ] ERR  WOPI::CheckFileInfo failed for URI [https://nc.example.net/index.php/apps/richdocuments/wopi/files/1937931_ocuinqirkrns?access_token=NY9WRZZjwd8B6JtwntrWNbSCsD2ZPkZb&access_token_ttl=0&permission=edit]: 0 . Headers: #011Body: []| wsd/Storage.cpp:703
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741260 [ docbroker_001 ] ERR  loading document exception: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1907
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741289 [ docbroker_001 ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/1937931_ocuinqirkrns] with URI [https://nc.example.net/index.php/apps/richdocuments/wopi/files/1937931_ocuinqirkrns?access_token=NY9WRZZjwd8B6JtwntrWNbSCsD2ZPkZb&access_token_ttl=0&permission=edit]: WOPI::CheckFileInfo failed: | wsd/DocumentBroker.cpp:1869
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741313 [ docbroker_001 ] ERR  Storage error while starting session on /index.php/apps/richdocuments/wopi/files/1937931_ocuinqirkrns for socket #24. Terminating connection. Error: WOPI::CheckFileInfo failed: | wsd/LOOLWSD.cpp:3592
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741350 [ docbroker_001 ] ERR  Socket #24 SSL BIO error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init (ECONNRESET: Connection reset by peer)| ./net/SslSocket.hpp:330
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741407 [ docbroker_001 ] ERR  Exception while invoking poll [docbroker_001] callback: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init| net/Socket.cpp:384
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741458 [ docbroker_001 ] ERR  Socket #24 SSL error: SYSCALL (5). (EPIPE: Broken pipe)| ./net/SslSocket.hpp:270
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741468 [ docbroker_001 ] ERR  #24: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1284
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741479 [ docbroker_001 ] ERR  Socket #24 SSL error: SYSCALL (5). (EPIPE: Broken pipe)| ./net/SslSocket.hpp:270
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741487 [ docbroker_001 ] ERR  #24: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1284
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741495 [ docbroker_001 ] WRN  Socket #24 is shutting down but 114 bytes couldn't be flushed and still remain in the output buffer.| ./net/WebSocketHandler.hpp:763
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741521 [ docbroker_001 ] ERR  No DocBroker found, or DocBroker marked to be destroyed. Terminating session ToClient-015| wsd/ClientSession.cpp:362
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741530 [ docbroker_001 ] ERR  Socket #24 SSL error: SYSCALL (5). (EPIPE: Broken pipe)| ./net/SslSocket.hpp:270
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741540 [ docbroker_001 ] ERR  #24: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1284
Aug 11 18:13:33 code loolwsd[5854]: wsd-05854-06637 2021-08-11 16:13:33.741548 [ docbroker_001 ] ERR  Invalid or unknown session [015] to remove.| wsd/DocumentBroker.cpp:1946
Aug 11 18:13:35 code loolwsd[5854]: wsd-05854-05866 2021-08-11 16:13:35.741886 [ prisoner_poll ] WRN  Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:2231
Aug 11 18:13:35 code loolwsd[6650]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/9vNMyyLde53NHRWb/tmp] failed: Permission denied.
Aug 11 18:13:35 code loolwsd[5867]: frk-05867-05867 2021-08-11 16:13:35.882979 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/9vNMyyLde53NHRWb/tmp].| common/JailUtil.cpp:68
Aug 11 18:13:35 code loolwsd[6652]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/9vNMyyLde53NHRWb/lo] failed: Permission denied.
Aug 11 18:13:35 code loolwsd[5867]: frk-05867-05867 2021-08-11 16:13:35.886558 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/9vNMyyLde53NHRWb/lo].| common/JailUtil.cpp:68
Aug 11 18:13:35 code loolwsd[6654]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/9vNMyyLde53NHRWb] failed: Permission denied.
Aug 11 18:13:35 code loolwsd[5867]: frk-05867-05867 2021-08-11 16:13:35.890511 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/9vNMyyLde53NHRWb].| common/JailUtil.cpp:68

```

**Screenshots**
It show the message and a menu bar with "File Edit View Insert Tools............... x"

**Desktop (please complete the following information)**
 - OS: Gentoo Linux
 - Browser: Chrome
 - Version: most recent, live builds

**Additional context**

Nextcloud still runs on a physical server
Code runs in an LXD container,  Ubuntu2004 distro, 
Both behind a HAproxy that terminates TLS & public valid certificates (Lets Encrypt), 
Each system has it's own virtual web host (code.example.net & nc. example.net )

Strange is the hostname is mentioned in the URI in the logs..   (GET nc.example.net ).

Note: the built in server is also not working.

**Comment by noci2012** [comment]
Not this IS NOT the same issue as previous issues that are about 6.4.10-5 or 6.4.10-5 about SNI   (Unless the SNI issue hasn't been fixed  in previous releases)...

**Comment by noci2012** [comment]
Side note: can you provide previous images from a working setup?

**Comment by Farenheid** [comment]
Same here. Some informations that could help: I encountered the problem with 6.4.10-10 and tried to revert to 6.4.10-9: same problem.
What changed on my setup: as yours, my Collabora server is running behind a haproxy reverse proxy, which runs on another server. The problem appeared when I upgraded the server running haproxy from Debian 10 to Debian 11. haproxy version was 1.4, it is now 2.2.9. I didn't make any change in my haproxy configuration. I suspect a change in haproxy behaviour which collabora doesn't like.

What I noticed in Collabora logs (I set them to "trace"): as far as I can see, collabora firstly requests a json file containing meta informations about the document it is about to load. There is a first socket timeout, but json data is eventually downloaded and  parsed by collabora.

Next step is downloading the actual document. Failure happens at that moment:
Socket #40 SSL error: WANT_READ (2) has_pending 0 bytes: 0.| ./net/SslSocket.hpp:236
Thus, it looks like a SSL problem. I tried downgrading haproxy security to support old ssl 3, tls 1.0 and tls 1.1, but it doesn't change anything.

I think the problem is not related to nextcloud, since it also happens with Collaborative Document plugin in Moodle (the plugin should embed a collabora document in a course).

Did you change something in your haproxy configuration ?

**Comment by jacotec** [comment]
@Farenheid Just found the same after hours and hours of trying around and investigating, being caught at CODE 6.4.9.x since weeks due to this.

I've opened an issue with my findings for this: #3199

**Comment by noci2012** [comment]
I am running haproxy 2.1.4 since March 2020.
2.4.0 since may 18th 2021
Without problems.

Problems started when  CODE was updated from  6.4.9.x  and still continue...

**Comment by Ashod** [comment]
Thanks for reporting this. I've followed up in #3199, but reading the logs here I can see that the WOPI request is behind SSL (https://nc.example.net), as also described.

Could it be that there are no SSL certificates provided in loolwsd.xml ? As a client, loolwsd needs to present SSL certificates to the server (in this case HAProxy) and it is up to the server to enforce their validity (or to ignore them altogether).

In 6.4.9 the client ssl certificates were handled differently, and probably because loolwsd was behind a reverse proxy no certificates were provided (I'm guessing, confirmation would be great), and this somehow worked.

Would it be possible to try providing valid ssl certificates (in loolwsd.xml: storage.ssl.cert_file_path, storage.ssl.key_file_path, and storage.ssl.ca_file_path) just to test this hypothesis please?

Thank you.

**Comment by jacotec** [comment]
@Ashod I already had set my HAProxy's SSL frontend to allow client connections without certificates or with invalid certificates yesterday for a test, but with no change.

I'll check the cert settings in loolwsd.xml later and play around with this nevertheless

**Comment by jacotec** [comment]
> In 6.4.9 the client ssl certificates were handled differently, and probably because loolwsd was behind a reverse proxy no certificates were provided (I'm guessing, confirmation would be great), and this somehow worked.
> 
> Would it be possible to try providing valid ssl certificates (in loolwsd.xml: storage.ssl.cert_file_path, storage.ssl.key_file_path, and storage.ssl.ca_file_path) and enable storage SSL (storage.ssl.enable) just to test this hypothesis please?

@Ashod I did this right now with "official" SSL Letsencrypt certs matching to my Collabora domain, unfortunately this did not help :-(

Let me know if there is anything else to try.

**Comment by Ashod** [comment]
A quick note that we have identified an issue and are working on a fix. Thanks everyone for the great help and patience.

**Comment by noci2012** [comment]
In the mean time i migrated all sites to only-office, the patience was thin, i needed a working setup.
