### ISSUE TITLE
iOS/Android zooming out leads to jumping/flickering

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3145]
**Describe the bug**
On mobile devices zooming in and especially zooming out leads to screen "jumping" or "flickering" (hard to find the right term). It's more an annoyance than a bug, but user expect smooth zooming and this is clearly not yet the case as the videos show:

Android:
![android_zooming](https://user-images.githubusercontent.com/1211300/131080095-9ae593b0-6b3c-405a-871f-1d489c87fa78.gif)

iOS:
![ipados_zooming](https://user-images.githubusercontent.com/1211300/131080114-178b7d65-ddb6-43cf-943a-75d931c39aa8.gif)

**To Reproduce**
1. Open a writer document on iOS/Android
2. Zoom in/out

**Expected behavior**
Zooming in and out should be smooth. On Andorid zooming in is quite smooth, but zooming out leads to missing tiles and jumps in many cases. On iOS both operations are not as smooth as they could be (maybe it's more obvious since the my screen is bigger - could very well be, that Android would behave bad in zooming in on a bigger screen as well).

**Actual behavior**
Zooming should be smooth.

**Smartphone**
 - Device: Andorid / iPad
 - OS: Andorid 8.1.x / iPadOS 14.x
 - both devices with their current C'Bra app snapshots (6.4.11 (1) for iOS) and the APK from yesterday (2021-08-26) for Android

**Comment by mmeeks** [comment]
Had a chat with Dennis; I think what we want is tweak the zoom animation rendering code so that:
- we select a source to interpolate from on each frame that has the most tiles covering the area that we are seeing.
- we also ask for more tiles mid-animation if the animation is taking some time, and/or is missing important tiles around the edge - ideally at the current zoom level.
Hopefully together this will give a better experience - as well as the nice pre-loading work =)
