### ISSUE TITLE
Add keyboard shortcuts to menu items in classic view menubar

### ISSUE THREAD

**Issue by alessioalex-1and1** [CollaboraOnline/online#3177]
**Is your feature request related to a problem? Please describe.**
It would be better UX-wise if the keyboard shortcuts were displayed alongside the menu items corresponding to them. For example Save (Ctrl + S), Cut (Ctrl + X) etc.

**Describe the solution you'd like**
Add shortcuts alongside the menu options were applicable, like in the following image:

![Menu items with shortcuts](https://cldup.com/GCJOlcBaWg.png "Menu items with shortcuts")

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by rpear** [comment]
I agree with this, as I often think the same for the notebookbar, e.g. the text "Bold" pops up when hovering over the "B" icon, it would be great if it said "Bold (Ctrl + B)", maybe this is hard due to different languages, if not, is it worth adding another ticket for the same thing for the notebookbar.
![Screenshot 2021-09-03 6 33 08 PM - Display 2](https://user-images.githubusercontent.com/80790599/131976859-f790beee-1813-4712-a241-c40bf40dde16.png)

**Comment by Ezinnem** [comment]
@pedropintosilva, please would you like to take a look at this?

**Comment by alessioalex-1and1** [comment]
closed via https://github.com/CollaboraOnline/online/pull/3178
