### ISSUE TITLE
HTML/JS sidebar: multiple outcomes when clicking/taping on "line style" button in the sidebar

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3323]
**Describe the bug**
When a drawing element is selected and the "line style" button is tapped/clicked in the sidebar, there are two possible outcomes and one of them seems to be wrong (but I'm not entirely sure).

If one taps/clicks on the left part of the button the "Line" dialog gets shown. If one taps/clicks on the "arrow down" part of the button, the "line selection" popup is shown. I tend to think that both parts of the button should show the "line selection" popup.

**To Reproduce**
1. Create/open a writer document in online (or the iOS app)
2. Insert a drawing element, e.g. "Insert > Shapes" then chose the rectangle
3. Select the newly added rectangle in the document
4. Open the sidebar
5. Click on the "line style" button in the sidebar

**Expected behavior**
It should not matter on which part of the button I click, the result should be the same.

**Actual behavior**
If one taps/clicks on the left part of the button the "Line" dialog gets shown. If one taps/clicks on the "arrow down" part of the button, the "line selection" popup is shown. I tend to think that both parts of the button should show the "line selection" popup.

**Screenshots**

Clicking on the "left" part of the button
![image](https://user-images.githubusercontent.com/1211300/135460038-3df6bb2a-8f01-4774-b0d4-03fa333e0fe5.png)

Clicking on the "right" part of the button
![image](https://user-images.githubusercontent.com/1211300/135460197-11f65651-7cc5-4299-a6e2-e6b82ed498b4.png)

**Online**
 - Firefox: 92.x
 - OS: Linux
 - Version: current version on https://staging.eu.collaboraonline.com/nextcloud/index.php - 21.06.1.0 (git hash: e5bbfc6) Served by: 7d76d5c7

**Comment by eszkadev** [comment]
@nikslor This kind of button in UI world is called "split button" it has 2 parts: left one calls default action and arrow gives you access to the dropdown with "other actions". see example: https://medium.com/nextux/drop-down-button-vs-split-button-f8e539fc0b78

@pedropintosilva do you think we can improve that so it will not be considered as a bug? maybe add visible split line?

**Comment by nikslor** [comment]
Thanks a lot @eszkadev for the explanation. I can't say much about the usefulness of such a split button (usability is by far not my field of expertise), but my gut feeling tells me, that it's not what users expect, and it also makes the widget hard to use with a finger.

My GTK desktop build also doesn't show that behavior (at least from a user perspective - I see, that the button is split in half and does an animation and then shows the "line selection" popup if I click on the right part of the widget).

I tend to say: let's only show the "line selection" popup - for both parts of the widget.

**Comment by pedropintosilva** [comment]
So I like split buttons but here there is not that much use for it :

* Split buttons are normally used to display not only the trigger menu but also to expose a let say most commonly accessed option or at least very important action that otherwise would be hidden under the menu (and with where the interaction cost would be otherwise higher). You can think of it as a solution to avoid complexity by having two components grouped as one button. E.g.: Nielson/Normans website has a good example of it https://www.nngroup.com/articles/split-buttons/
  * This does not seem the case because we are grouping a dialog trigger (and wills show yet more options) with a menu trigger here 
* Plus we already a button  ![image](https://user-images.githubusercontent.com/65948705/135858369-9c010678-5b2e-48a8-87d8-51a63015453c.png)  that opens the line dialog
* The Desktop counterpart has a simple drop-down (so chances are users expect that as well on CO)


If we still want to emphasize that user can see more options, then we could just add a bottom menu item to each drop-down on the sidebar that has more options like so: 
![image](https://user-images.githubusercontent.com/65948705/135865024-3edf7370-6433-4b30-8338-51ff03818d41.png)

____

BTW I also noticed that in some cases, where each line is an image with border, we need to fix the margin rule that is affecting these menu entries.

**Comment by eszkadev** [comment]
fix: https://github.com/CollaboraOnline/online/pull/3339

instead of calling uno command for a button now we trigger correct action (for line style it will open dropdown)

**Comment by eszkadev** [comment]
I'm closing the ticket as now arrow and icon have the same behaviour (dropdown menu)
