### ISSUE TITLE
Data are not saved in spreadsheet files when mounting is disabled

### ISSUE THREAD

**Issue by gmasei11** [CollaboraOnline/online#3604]
**Describe the bug**
Data are not saved in a spreadsheet document when mount_jail_tree setting from loolwsd.xml is set to false. 

**To Reproduce**
1. Set mount_jail_tree setting from loolwsd.xml to false.
2. Start Collabora Online.
3. Open a spreadsheet file
4. Type some text in one or more cells
5. Save
6. Type something in a cell or insert an image or insert a chart
7. Save
8. Close the session
9. Reopen the file in a new session

**Expected behavior**
After reopening the file (step 9) the file should reflect the changes made at steps 4 and 6.

**Actual behavior**
The changes made at step 6 were not saved.

**Screenshots**

https://user-images.githubusercontent.com/73231749/141302554-67a8fd0e-5cae-4fe6-b23f-006f185595d6.mp4

**Desktop**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: chrome, firefox
 - Version: 
    Debug
    LOOLWSD 21.11.0.0 (git hash: 6b4dc708)
    Served by: 2d93a295
    LOKit Collabora Office 21.06.5.2 (git hash: c274eea)

Also, this is reproducible in 6.4.10 and 6.4.14

**Comment by gmasei11** [comment]
@Ashod @mmeeks I partially diagnosed the problem. It seems that the issue was generated by this commit: [wsd: move convert-to docs into the jail](https://github.com/CollaboraOnline/online/commit/fad4222a2a91785e714df7ffad1ffd4ddb8f4142). To be more precise, by the [hard linking part](https://github.com/CollaboraOnline/online/commit/fad4222a2a91785e714df7ffad1ffd4ddb8f4142#diff-5d08e62594b9952da25eb814e4567987fc57740d3c665dc789b824e26c2da6bbR351) of it. Because of it the copying is [skipped](https://github.com/CollaboraOnline/online/blame/master/wsd/Storage.cpp#L420) after the file was saved in core:

if (_isCopy && Poco::File(getRootFilePathUploading()).exists())
    FileUtil::copyFileTo(getRootFilePathUploading(), path);

For whatever reason, at the second save (step 7), the inode for the file inside the jail changes to a different one than the inode for the original file (the hard linking is canceled), but the copying still is not performed because of the above condition.

If the **mount_jail_tree** is set to true then hard linking fails and _isCopy becomes true which triggers a file copy at every save. That's why it doesn't reproduces when mounting is enabled.

We can replace the _isCopy in condition with a check for the same inode or diagnose further why the inode changes in jail.

It seems that this is a local storage issue. I'm not sure if local storage is used in other scenarios than local file editing. If not then in practice a WOPI server is used so it seems that this is not so critical. However, since local file editing is used in debug mode I think that we should still fix it.

**Comment by Ashod** [comment]
@gmasei11 Thanks for the info. Will dig deeper and revert back.

**Comment by Ashod** [comment]
> For whatever reason, at the second save (step 7), the inode for the file inside the jail changes to a different one than the inode for the original file (the hard linking is canceled), but the copying still is not performed because of the above condition.

Does this hint that the underlying file-system has copy-on-write enabled? That's what the above description seems to imply. Copy-on-write is unexpected and should break things badly, yes. (ZFS deduplication, for example, would give similar results. Basically, creating a new copy a linked file when it's modified.) 

> If the **mount_jail_tree** is set to true then hard linking fails and _isCopy becomes true which triggers a file copy at every save. That's why it doesn't reproduces when mounting is enabled.

Yes, I believe that's correct.

> We can replace the _isCopy in condition with a check for the same inode or diagnose further why the inode changes in jail.

That's one solution, but there is a better one. See below please.

> It seems that this is a local storage issue. I'm not sure if local storage is used in other scenarios than local file editing. If not then in practice a WOPI server is used so it seems that this is not so critical. However, since local file editing is used in debug mode I think that we should still fix it.

Yes, this should be isolated to local-storage files and only on file-systems that break hard-links on write (i.e. with copy-on-write). For debugging on such a file-system, it can be painful indeed. (On production systems, local storage should never be enabled, for security reasons.) However there is a solution.

We have been meaning to unify the storage layer to avoid having separate and different handling of local files from those coming from a wopi host. This has been implemented and I've tested it and it works on my system. (For reference: https://github.com/CollaboraOnline/online/commit/d9795fff2ee54839cf1ce5304d59d0b9fc886269)

**Can you please use `debug.html` instead of `loleaflet.html` in the URL ?** 

(While I couldn't reproduce the issue locally, I confirmed that `debug.html` doesn't use the LocalStorage code you referenced. I expect it to work for you.)

Hope this helps!

**Comment by Ashod** [comment]
@gmasei11 any luck trying the suggestion above? Feel free to close if all is well. Thanks!

**Comment by gmasei11** [comment]
@Ashod Thanks for your feedback! Sorry for late reply. :( I didn't manage to fully evaluate your feedback, stuck with some other stuff. However, I tried debug.html and it works and I couldn't reproduce the issue anymore with local files.

Also, there is something that I don't fully understand: on the one hand you confirm that this is isolated to handling of local-storage files but, on the other hand, you say that you unified the handling of local-storage files and files coming from wopi server. In the latter case if the same code that triggered this issue is used then we must further investigate this issue because it is critical if reproducible in production. Judging by local file editing test results it seems that the issue was fixed. However, I'm puzzled by the fact that the code that triggered the issue is still there. I mention again that I didn't studied thoroughly the changes you mentioned in your feedback.

Taking into account the above considerations, do you think that we should continue with investigation (and why) or we should abandon it (and why) ?

Thanks!

**Comment by Ashod** [comment]
@gmasei11, sorry for the late reply; this dropped from my radar.

Perhaps I wasn't clear enough. Serving documents from local files should *never, ever* be used in production. It's *only* for testing/debugging.

The issue you were facing is in *old* the local-file storage logic, which is now deprecated in favor of debug.html. The debug.html file uses the same WOPI layer *even for* serving local files. So, if anything, it confirms that the WOPI layer is working correctly, even when you are testing with a local file (because we route the logic though the WOPI layer, exactly for the expressed purpose of exercising the same production code).

So, you hit a bug in a test code-path that is now deprecated. Nobody in production would use that (without major security issues). The new test code (debug.html) doesn't suffer that bug *and* it uses the same storage logic as used for WOPI hosts in production, thereby giving us more confidence in what we are testing.

Bug, if you still feel there is anything to investigate, please report. At this point, I'd say this issue is closed (and you may close this ticket when you're happy with the above).

Thanks!

**Comment by gmasei11** [comment]
@Ashod Thanks for your clarification! The ticket is closed!
