### ISSUE TITLE
Docker build fails with "chown: invalid user: ‘cool:cool’" Ubuntu 

### ISSUE THREAD

**Issue by sebastianfischer** [CollaboraOnline/online#3707]
**Describe the bug**
docker build fails with error "chown: invalid user: ‘cool:cool’"
Branch: master last commit e668110461396fe2b79d32ad0daf475ce6f81d55

**To Reproduce**
1. Go to 'docker/from-packages'
2. Execute `docker build --no-cache --build-arg type=cool --build-arg secret_key=<....> -t mydomain/cool -f Ubuntu .`
3. See error

**Expected behavior**
build should build without fail

**Actual behavior**
build fails because of missing user

**Workaround**
subsitute `cool` with `lool` in file `docker/from-packages/scripts/install-collabora-online-ubuntu.sh` and execute with `docker build --no-cache --build-arg type=lool --build-arg secret_key=<....> -t mydomain/cool -f Ubuntu .`

**Comment by Ezinnem** [comment]
You experienced the error because the Docker scripts were updated recently for the coming release.

The scripts supporting the 6.4 version have been saved to distro/collabora/co-6-4 branch.

@sebastianfischer, please you can try again from the distro/collabora/co-6-4 branch.

**Comment by zygimantus** [comment]
I am facing same issue, not sure why this is closed, since @Ezinnem the branch you mentioned also contains `lool` user https://github.com/CollaboraOnline/online/blob/distro/collabora%2Fco-6-4/docker/from-packages/scripts/install-collabora-online-ubuntu.sh which needs to be replaced to `cool`. Is it only needed for collabora online installation?
