### ISSUE TITLE
Can't print documents

### ISSUE THREAD

**Issue by gjongenelen** [CollaboraOnline/online#3784]
**Describe the bug**
Clicking the print button in Collabora results in a 404 error

**To Reproduce**
1. Create new document
2. Click print

**Expected behavior**
A printer-view opens with page preview

**Actual behavior**
A printer-view with empty page is shown, clicking print does nothing

**Client details:**
 - OS: MacOS
 - Browser: Safari

## Server details

**Operating system**: Ubuntu 20.04

**Web server:** Apache 2.4.41

**Database:** MySQL 8.0.27

**PHP version:** 7.4

**Nextcloud version:** 23.0.0 (also present in NC22)

**Version of the richdocuments app** 4.2.3

**Version of Collabora Online** 21.06.8.1 (COOLWSD 21.11.0.3)

<details>
<summary>Logs</summary>

No logs found

</details>

**Comment by wget** [comment]
Hello there, 

Thanks for your report.

I have been able to reproduce the issue on our production instance based on COOL 21.11.05, running on Ubuntu 18.04 with Apache.

The device is a MacBook Pro "M1 Pro 14" with macOS Monterey 12.0.1.

<img width="1512" alt="bug-report-online-3784-0001" src="https://user-images.githubusercontent.com/2997662/145228294-a6c1ffed-d301-4b99-9ac2-32e433b49e2e.png">

I opened a document and tried to print it.

Safari first asked me to confirm I was really willing to print a document.

<img width="1512" alt="bug-report-online-3784-0002" src="https://user-images.githubusercontent.com/2997662/145228533-c31b1ad8-66cc-4eca-9b0b-ca4ab3c659da.png">

Then it tried to detect my network printer and install the required driver (this was the first time I was trying to print something on that machine).

<img width="1512" alt="bug-report-online-3784-0003" src="https://user-images.githubusercontent.com/2997662/145228629-08208b8a-76c9-4f16-9cd4-4592658ec3ba.png">

Then I noticed in the printing dialog that the document preview was blank/empty. I thought it was a rendering bug, but when confirming the printing process, I got an empty page from the printer like the preview.

<img width="1512" alt="bug-report-online-3784-0004" src="https://user-images.githubusercontent.com/2997662/145228752-e01b299f-e799-43db-a300-454ec16979fa.png">

I tried on Firefox and there, the problem was worse. Firefox didn't ask me to print at all but downloaded a PDF rendered version of the document instead of offering me the printing feature.

![bug-report-online-3784-0005](https://user-images.githubusercontent.com/2997662/145228879-269f336f-0f22-4c82-99f6-1f2acbe3e5b4.png)

So I can confirm your bug. We can even subdivide it is several sub-tasks (problem 1: Safari, problem 2: Firefox).

I tried on my Arch Linux based laptop and the problem with Firefox could be reproduced there as well: the document was downloaded as PDF instead offering me the printing feature.

**Comment by sebastiaanveld** [comment]
The issue is not only with printing but also when using the "See revision history" function, at least with Firefox.

Client details:

    OS: Win 10 build 22000
    Browser: Firefox 94.0.2


![afbeelding](https://user-images.githubusercontent.com/37268999/145247033-8415f796-d91f-49e9-8806-b00f1f62ce0a.png)

**Comment by joergmschulz** [comment]
imho the behaviour that a .pdf is downloaded for local printing is the correct one. You simply print this result.

**Comment by gjongenelen** [comment]
> imho the behaviour that a .pdf is downloaded for local printing is the correct one. You simply print this result.

From an UX perspective, I disagree. Downloading/exporting as PDF should be another functionality (as it is right now).

**Comment by gitgt** [comment]
This was old report that should be retested with current Online 22.05.13. Please do so that we know if problem is gone or MacOS only.

**Comment by sebastiaanveld** [comment]
On Win 11 with latest Firefox and CODE 22.05.13.1 with NC 25.0.5 I do not see the problem anymore.

**Comment by gitgt** [comment]
No response for Mac, let's assume this was also resolved there. If not, feel free to comment.

**Comment by joergmschulz** [comment]
true, on MAC print works perfectly.
