### ISSUE TITLE
Sidebar: Paragraph align vertical

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3805]
the arrangement of the writer sidebar section with activated vertical align elements didn't fit perfect

![image](https://user-images.githubusercontent.com/8517736/145110325-a1f0a852-6078-4dbb-aa14-e6754d1674cb.png)

**Comment by Ezinnem** [comment]
The screenshot looks a lit different from what I have on my end.

Please what is your screen resolution?

**Comment by Ezinnem** [comment]
@pedropintosilva @eszkadev

**Comment by Andreas-Kainz** [comment]
I will fix this bug, if it's really a bug myself. It's here as issue to have it on my to-do list.

**Comment by pedropintosilva** [comment]
So it took me a while to understand where this bug came from and how #3873 is supposed to solve it. I discover that it's basically a regression coming from the following commit 27be41fb787762111cd1212524e3f3c48b4d8cb1 (note please in the future add the hash of the commit from where the regression started, and maybe better to revert the commit first with `git revert [commit-hash-number]` and then add additional commits if necessary above it) .  

Please see notes in the closed PR
