### ISSUE TITLE
iOS app: not possible to add a comment in a writer document (with hardware keyboard)

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#402]
**Describe the bug**
When taping on the "Comment" button in the notebookbar on 6.4.0 (5) the dialog to add the actual comment shows up for a wink of an eye and then will vanish again. It's not possible to actually type something into the dialog.

**To Reproduce**
1. Open a writer document using the iOS app
2. Tap on Home > Comment button

**Expected behavior**
A dialog where I can enter my comment shows up.

**Actual behavior**
The dialog pops up and vanishes immediately.

**Tablet**
 - OS: iOS 14.1
 - Version: 6.4.0 (5)

**Comment by thebearon** [comment]
@nikslor, this works for me in app version 6.4.0 (9), please retest.

**Comment by tml1024** [comment]
Can reproduce in a fresh build with a hardware keyboard (the Smart Keyboard Folio). Tap the "Insert" tab of the notebookbar, then tap the "Comment" button. The window in which one should type in the comment shows up, but  if I type on the hw keyboard, the text does not show up (there is no caret in the text field so that isn't really expected either). If I tap into the field, the window disappears.

Without hardware keyboard, it is even worse. the window to enter the comment does not show up at all.

**Comment by tml1024** [comment]
Reverting 68d2d9cbd42f57418927bf3e619e372bb674b218 fixes this problem, too. (When using a hardware keyboard.) Has no effect when using on-screen keyboard. So I probably will do that.

**Comment by nikslor** [comment]
This issue is fixed in the current build - tested with 6.4.0 (10).

Is it possible to add an automatic test for this? (I believe it's hard to "simulate" a hardware keyboard, nevertheless it would be awesome, if it could be tested automatically)

Should we close the issue as being fixed?

**Comment by nikslor** [comment]
@tml1024 I think we can also fix this one. Do you take care of it?
