### ISSUE TITLE
Nextcloud - Built-in CODE Server: Could not establish connection to the Collabora Online server

### ISSUE THREAD

**Issue by ewan86** [CollaboraOnline/online#429]
I am unable to use the built in code server to open documents in Nextcloud using Collabora online
To Reproduce

1.install Collabora Online - Built-in CODE Server app and enable
2. install Collabora online app
3. try to open office document - failed to load collabora online please try again later
4. Go to code server settings - says server is enabled
5. Click settings link, get 404 error
5. Go to Collabora online settings, says Could not establish connection to the Collabora Online server.
Expected behavior

Documents to open in libreoffice online within nextcloud and for the settings for libreoffice online to say connected. And settings link to open
Screenshots

![image](https://user-images.githubusercontent.com/13614310/97106507-f7f93f80-16b9-11eb-8302-6ecbf2448cf6.png)
![image](https://user-images.githubusercontent.com/13614310/97106514-00517a80-16ba-11eb-9415-971cd588d642.png)

OS/snapd/snap version

ubuntu 18.04

Name Version Rev Tracking Publisher Notes
nextcloud 19.0.4snap1 23743 latest/stable nextcloud✓ -

snap version
snap 2.47
snapd 2.47
series 16
ubuntu 18.04
kernel 4.15.0-121-generic

**Comment by mrkara** [comment]
@ewan86 Thank you for taking the time to report this issue! :)

But Built-in CODE Server has [its own repo](https://github.com/CollaboraOnline/richdocumentscode), and thus the related issues need to be [reported there](https://github.com/CollaboraOnline/richdocumentscode/issues). Could you please move this report to there?

By the way, if you are getting a 404 error while trying to see the settings, it is highly probable that this is related to something in your app installation went wrong rather than a bug in the Built-in CODE Server itself.

Thank you!
