### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by florealcab** [CollaboraOnline/online#4382]
Application is so beautiful, but is missing a dark mode.

An option to choose theme between light and dark should be a good thing for users eyes :)

**Comment by danir-de** [comment]
Doing this automatically via reading the current system dark-mode would be even better: If the user is in dark mode, automatically use dark mode, if not use light mode.

**Comment by florealcab** [comment]
Yes, an automatic behavior is a good practice. Some times, this setting could not be detected (on some linux systems for example) so the common way to achieve that is an option with 3 choices :
- Automatic (follow system setting)
- Dark
- Light

If we use it on nextcloud (my case), could also follow the nextcloud parameter for dark theme

**Comment by zak39** [comment]
Please, if you want to make a dark mode, you should not change the background only.

The background color, the color of the paper and the color of the icons should be studied.

I see many apps that only change the background color.

A good example, the "grafikart website" : https://grafikart.fr/

When we switch to dark mode, the fonts, buttons and many more change too.

It's very pleasant to read

What do you think ?

**Comment by danir-de** [comment]
@zak39 I understand where that idea is coming from, but that is a whole other topic.

Also applying a dark theme to the document would make it unusable for most people, since documents cannot be shared or printed in dark mode and would have to constantly be converted between a light and dark color scheme. 

This might work for "simple" proprietary apps, but for full document suits where a user can easily change the text color to black, that color has to stay black and cannot be "converted" into another color just for a dark mode, since that would completely destroy a document. 
Even if you would take that into account... How should that black text be displayed on a dark mode page? Should it be converted to white or should it stay black? There is another element that's darkgray. Should that be displayed as lightgray? What happens with the dark transparent image, one user has inserted in the document? You can't simply invert that!

I think that this issue should firstly focus on an UI-only dark mode, if you want, you can tackle the problem in another issue later - first things first!

**Comment by zak39** [comment]
Yes, I agree with you :wink: 

This is precisely one of the mistake I saw on some applications.

I'm sorry, I misspoke ^^'

I meant to say, if you set the same black color as the GitHub color for the background. I think the contrast will be high and it's very hard to focus on the document

Do you know what I mean ?

**Comment by Andreas-Kainz** [comment]
The JS UI stuff use now var-colors from https://github.com/CollaboraOnline/online/blob/master/browser/css/color-palette.css 

![Screenshot_20220314_010004-1](https://user-images.githubusercontent.com/8517736/158085165-bd730ace-29b4-43e7-99aa-9177e2c26aa5.png)

"only" the part that come from core had to be renderd for dark mode therefore there is a setting at LibO in Options -> Application Colors where an Scheme: LibreOffice Dark is already available. So core has to be run with the Application Color / Scheme and than we can have dark mode.

![image](https://user-images.githubusercontent.com/8517736/158084976-db7f1c2f-1a7c-442e-a4af-e28c20c77423.png)

Colibre Dark Icon theme is in LibreOffice core master build since today, so also an Icon theme will be available for dark mode.

Task's for COOL dark mode:

- [x] JS UI use color-scheme.css var colors
- [ ] color-scheme-dark.css file has to be done and loaded when dark mode is activated (can be done easily)
- [x] colibre dark icon theme (is already in LibO core master and can be added to cool)
- [x] LibO Core UI part has to be renderd in dark mode (can be done with load LibO with Application scheme LibO Dark)
- [ ] Core part has to be run with Application Scheme var AND defined by users how will use dark mode
- [ ] dark mode setting has to be added to the user UI and the server settings

**Comment by Andreas-Kainz** [comment]
The biggest part use var colors for the JS UI was alredy done. Next would be the connection to core. @pedropintosilva what do you think? If someone can do the connection to core, I will do the icon task and color-scheme-dark.css task.

**Comment by ChaosBlades** [comment]
The worst part about this is that you can't even use [Dark Reader](https://github.com/darkreader/darkreader) to work around this not being implemented. Colabora Online only works with the Filter method which is flawed and since this is using the same url as nextcloud if you have that dark theme enabled it conflicts. So if you open a document in nextcloud you have a nice dark UI then you are blinded by a pure white screen. If you disable the nextcloud dark theme then use Dark Reader to make both dark you are still stuck with the Filter mode which is even more flawed on nextcloud. I'll stick to using the desktop LibreOffice apps until this gets implemented. White UIs give me headaches after a while even with monitor brightness turned down.

**Comment by LorenAmelang** [comment]
Just want to add that a few of us with horrible vision use "Dark Mode" to get maxium contrast with minimum white glare. The ideal for me is pure white text on pure black background. But that should not change the actual document as seen by other people! 

For most websites, the Dark Reader extension does a very nice job of turning a normal page into my high contrast view. Safari Reader unfortunately limits the text at half-brightness, while leaving graphics at full white, which is horrible for me. 

Libre Office (on Windows) can be set to show _most_ file content with max contrast white on black, but a few tricky conditions like selecting existing text in a field (in _some_ documents), or using the text-to-columns preview, are just invisible. In any dark mode solution, there needs to be a handy and obvious button to enable and disable it, so those quirks can be coped with. Libre also shows a lot of icons and controls that don't respond with either the top header dark mode or the content settings. 

Collabora on iPhone or iPad with the Apple "Smart Invert" actually looks pretty good to me. I have an 'Automation' that turns on "Smart Invert" whenever I open Collabora, and at least for simple data collection I'm pretty happy with that!

**Comment by Andreas-Kainz** [comment]
LibO has colibre-dark.svg icons already the question is how to select between light and dark colibre.svg icons?
