### ISSUE TITLE
Ambiguous description of "Export as..." functions in the NotebookBar

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#4564]
**Is your feature request related to a problem? Please describe.**
In the File Tab of the NotebookBar the "Export as..." functions are not clear enough. It is easily confused with the "Save as..." function. 

 
**Describe the solution you'd like**
An "Export as..." note after the print symbol could make it clearer that the following buttons are intended for export. (However, a separate "Export as..." button would also be conceivable). 

**Describe alternatives you've considered**
I repeatedly click on the "Save as..." button instead of the export functions when I want to export files. For me, the current solution is not intuitive, although I am trying to learn it...

**Additional context**
![grafik](https://user-images.githubusercontent.com/51329893/162272915-490753b0-e8fb-47ce-8c7e-10fb2fd94345.png)

**Comment by thebearon** [comment]
@pedropintosilva, what do you think?

**Comment by pedropintosilva** [comment]
I agree that the current situation is not ideal. We should communicate without shadow of a doubt that the user can:
- Save the current document as another format or same format but different name (**save as**)
- "Export as" AKA **Download** to his local machine the current document as any of the available formats

So that we are doing right now is skipping one step (in conveying the "download" part) and jumping right into the "as" part resulting in some users getting confused (and spending more time in scanning all the options)

**Comment by pedropintosilva** [comment]
I have discussed this with at the time @gmasei11 and @alessioalex-1and1 and we agree that we should allow for another way for the integrator to display those options (specially because they might want to add other btns and the white space is needed). And so @alessioalex-1and1 wen ahead and created a patch exactly for that (already merged): https://github.com/CollaboraOnline/online/pull/4283

![image](https://user-images.githubusercontent.com/65948705/162464508-2876efbe-56b2-4952-85e6-9e0239032fdb.png)

**Comment by pedropintosilva** [comment]
So I think what we can do right now and that would require the less amount of effort is:
- Improve that download as icon so it does not feel out of place
- Make it a bigtoolitem (bigger)
- Have the `<group_download_as` option set to true by default in the next CODE release
- Wait/request for any user feedback on the topic

**Comment by pedropintosilva** [comment]
then depending on the feedback we can regroup and think if instead what it makes sense is to introduce a complete new component: `"tab group label"`

**Comment by pedropintosilva** [comment]
fixed
