### ISSUE TITLE
Menubar and Tabbedbar use same Font size

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4686]
Can we harmonize the font size of menubar and tabbs at tabbed bar header area?

#### menubar
![menubar](https://user-images.githubusercontent.com/8517736/165300397-a962702f-dbc3-43d1-a7d6-c03b7f509e8c.PNG)

#### tabbedbar
![tabbed](https://user-images.githubusercontent.com/8517736/165300421-20721fab-c0e9-4441-8156-46851eedc597.PNG)

**Comment by Andreas-Kainz** [comment]
@pedropintosilva ?

**Comment by pedropintosilva** [comment]
I would refrain from making it the same size because they are different in nature. One is a tab another one is a menu item, by making them equal in size (and specially with UI switcher available now):
- We are blurring the line between compact and tabbed view making it harder to spot which is which 
- We are, even if unintended, saying to the compact view user that that top menu is actually something else
