### ISSUE TITLE
Missing actions for file extensions in the hosting/discovery xml

### ISSUE THREAD

**Issue by goncalo-synergy** [CollaboraOnline/online#4690]
Hi everyone!

I have some doubts about the hosting/discovery xml, in particular about the actions for each file extension.

For example, '.docx' documents only have the "edit" action, and for '.dotx' documents only the "view" action is available.

I believe this happens to all types of files, so I assume it is on purpose. Is there a specific reason for that?

What should we use if the action that I am looking for does not have the correct extension?

Thanks!

**Comment by timar** [comment]
docx files are editable, dotx files are not, because it is not yet implemented what to do with templates. User may want to edit the template itself or create a new document based on the template. What is your use case in particular?

**Comment by goncalo-synergy** [comment]
> docx files are editable, dotx files are not, because it is not yet implemented what to do with templates. User may want to edit the template itself or create a new document based on the template. What is your use case in particular?

I want to view/preview files, should I use dotx for that?
That would mean I had to convert the docx to dotx every time before opening it to view/preview.

**Comment by timar** [comment]
discovery.xml states what the program is capable of. You can edit it in your instance, if want view only. Also, you can make the files read-only in your integration, then they won't be opened for editing. Of course the worst solution would be to rename the files, I do not recommend that.

**Comment by thebearon** [comment]
I presume this has been clarified, and can be closed. If there are further questions, please use the forum: https://forum.collaboraonline.com/

**Comment by donquixote** [comment]
> discovery.xml states what the program is capable of.

This means that "edit" implies that you can also "view".
In case of pdf, also "view_comment" would imply "view".

This means if you want to check whether a file is viewable, you need to implement a fallback lookup to "edit" and "view_comment".

If somebody would alter the discovery.xml to specify different urls for "edit" and "view_comment", while not specifying anything for "view", it is now unclear which url should be used for "view", because the fallback logic is not documented anywhere.

A related question is whether the discovery.xml has any effect on Collabora itself. From what I understand, it is meant for external apps to consume.
