### ISSUE TITLE
collapsed notebookbar no bottom border

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#5112]
In the notebookbar layout there is a bottom gray border line see:
![Screenshot_20220805_170041](https://user-images.githubusercontent.com/8517736/183104804-13781bdb-d7dc-425f-961d-a478b236e279.png)

when you collapse the notebookbar there should be also a bottom gray border line from my point of view
![Screenshot_20220805_165918](https://user-images.githubusercontent.com/8517736/183104701-e7b4706d-c5a4-4b51-a663-17bf4a5442d3.png)

bottom border line
![Screenshot_20220805_165918](https://user-images.githubusercontent.com/8517736/183105323-1e6a10c3-dfba-40c3-8f8f-4fe215f30b8a.png)

**Comment by pedropintosilva** [comment]
hm I'm afraid that was intentional because:
* The tabs parent never has border. Meaning the tabs are not really "glued" to tabs' content
  * So it would be rather strange to suddenly add bottom border once the tab content is not there
* It allows for a less "framed" interface around the document. So less clutter where the document remains the centerpiece
  * This is even more evident when also sidebar is collapsed
