### ISSUE TITLE
CODE 22.05 + Nextcloud Office 6.2.0 (richdocuments) + Apache2 Reverse Proxy = not working

### ISSUE THREAD

**Issue by porrarafaelmano** [CollaboraOnline/online#5192]
I'm trying to install Collabora CODE on a Nextcloud Server, but Nextcloud Office app (richdocuments) could not load Collabora (it's not even reachable).

So I decided to downgrade CODE from 22.05 to 21.11 

**_/etc/apt/sources.list.d/collabora.sources_**                 
```
_Types: deb
URIs: https://www.collaboraoffice.com/repos/CollaboraOnline/21.11-CODE/CODE-debian11/
Suites: ./
Signed-By: /usr/share/keyrings/collaboraonline-release-keyring.gpg_
```

CODE 21.11 is reachable, but Nextcloud Office (richdocuments) 6.2.0 failed to load a document file. 

And again, I decided to downgrade Nextcloud Office (richdocuments) from **6.2.0** to **6.0.0**

And finally, it's working!

**Distro**
Debian 11

**Nextcloud version**
24.0.4

**coolwsd.xml:**
SSL disabled
SSL termination enabled

**Apache2** 
Using reserve proxy (SSL termination) configuration from [official documentation ](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html)

**Comment by avatar1024** [comment]
I had the issue when upgrade to the Nextcloud office app 6.2.0 on both instances. I got a "document failed to load" message when trying to open a doc.

What solved was:

1. Install the Buildt-in CODE server app in nexctcloud.
2. Connect to this instead of my own Collabora server app
3. Open a document
4. Then go back to the settings and connect to my own server again.

Things been working fine ever since and this on both instances.

Yet people should look into what cause the issue in the first place with the Nextcloud Office app 6.2.0

**Comment by isdnfan** [comment]
two NC25.0.2 (Nextcloud Office aka richdocuments 7.0.1) and Collabora CODE 22.05 work perfectly together (as Docker containers on same host).
take look here and work through troubleshooting steps: https://help.nextcloud.com/t/nextcloud-collabora-integration/151879

**Comment by reos-rcrozier** [comment]
Nextcloud 25.0.3 and CODE 22.05 (standalone, running on same server, not Nextcloud built-in) also working fine for me.
