### ISSUE TITLE
The horizontal and vertical scroll bars are too thin, please fix them, thank you!

### ISSUE THREAD

**Issue by daxia2002** [CollaboraOnline/online#5471]
**Describe the bug**
![微信截图_20221115160355](https://user-images.githubusercontent.com/62735371/201863255-b71de97a-beda-48c9-9add-f8b3f70e1ebe.png)

**To Reproduce**

**Expected behavior**

**Actual behavior**
A 
![微信截图_20221115160355](https://user-images.githubusercontent.com/62735371/201863301-1c824411-ac72-4f4a-bfe9-4b06ec290f23.png)
clear and concise description of what actually happens.

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by SakshiT25** [comment]
@daxia2002  Hi, I want to work on this issue. Please assign me this.

**Comment by Ezinnem** [comment]
@pedropintosilva

**Comment by Ezinnem** [comment]
@pedropintosilva

**Comment by pedropintosilva** [comment]
Thanks @daxia2002 for reporting it and yes there is one last missing step on our recent scrollbar improvement changes. The problem is not really the active area because that is quite large, meaning that the user doesn't actually need to be precise to interact with the scrollbar as you can see in the [ following picture](https://user-images.githubusercontent.com/65948705/201871133-dd450b09-f2f2-4218-a525-9c087e019797.png). Nevertheless, as I state before, we are missing the hover state which will improve user experience. 

@SakshiT25 Awesome! I have created the respective easy hack :) #5473
