### ISSUE TITLE
cool-api.html

### ISSUE THREAD

**Issue by timar** [CollaboraOnline/online#5519]
**Describe the bug**
What is cool-api.html and is it still relevant?

**To Reproduce**
See https://github.com/CollaboraOnline/online/blob/master/browser/cool-api.html

**Expected behavior**
Probably this document should be on sdk.collaboraonline.com with updated content.

**Comment by pedropintosilva** [comment]
Sorry I didn't see this earlier. So that cool-api.html file has a very unambiguous name. I have looked around and it seems its contents are about the code itself. More specifically the (cool modified)leaflet, how to initialize map etc. should we put it in the SDK and if so under what? (We could crate a new sub level called `COOL API` under Documentation but then it will need some explanatory paragraph at the beginning )

Let me know and I can try to add it

**Comment by timar** [comment]
@hfiguiere removed cool-api.html.
