### ISSUE TITLE
iOS App: "Help > SendFeedback" not working

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5841]
**Describe the bug**
The button "Send > Feedback" is not working in the current TestFlight Version (22.05.202302092239)

If sending feedback is not possible from the iOS app, the button should not be visible (IMHO).

**To Reproduce**
1. Open a writer document in the TestFlight iOS app
2. Change to the "Help" tab
3. Tap on "Send Feedback"

**Expected behavior**
A dialog should show up (I guess)

**Actual behavior**
Nothing happens

**Tablet**
 - OS: iPadOS 15.6.1
 - Version: 22.05.202302092239

**Comment by plubius** [comment]
I have seen this too in several toolbar icons. Tapping toolbars like these leaves it drawn like it is still pressed so my current theory is that an unexpected exception is being thrown by the underlying LibreOffice code.

**Comment by plubius** [comment]
I think I know why this toolbar button is failing: the JS code is trying to load the URL in window.feedbackUrl defined in cool.html:

window.feedbackUrl = '%FEEDBACK_URL%';

What the Online server code does is replace sever %...% strings when it serves cool.html and other files to the web client. But this code is never executed in the iOS app because the "server" part of the app directly loads local files directly into the WKWebView.

It makes sense to me that Online dynamically replaces these strings with each request because the values can be update on the server and pushed to the web client. But in the iOS app, the "server" part is bundled locally in the app so I would like to avoid duplicating the dynamic replacement of these strings.

So, my current solution is to edit the makefile to do the string replacement during the build (iOS builds only) instead of at runtime.

Below are the 4 strings that need to be replaced on iOS. If anyone knows of others, let me know:

%UI_RTL_SETTINGS%
%WELCOME_URL%
%FEEDBACK_URL%
%BUYPRODUCT_URL%

**Comment by plubius** [comment]
I have this bug and now the Help > Send Feedback button is hidden by default. The button was displayed because window.feedbackUrl was set to '%FEEDBACK_URL%' which is an invalid URL. In the Online releases, %FEEDBACK_URL% is replaced dynamically with an empty string or a client's custom ticketing or feedback website.

I found out that there isn't any such custom website for the iOS or Android apps so, with my fix, %FEEDBACK_URL% is now set to an empty string. That, in turn, causes the JS code to hide the Send Feedback button.

While fixing this bug, I also added code to set the base text direction via JS so that RTL languages have the correct layout like in [this screen snapshot](https://user-images.githubusercontent.com/104370511/224515373-2a085134-e8d9-4864-a9e2-02f6f248fb96.png).

**Comment by plubius** [comment]
> While fixing this bug, I also added code to set the base text direction via JS so that RTL languages have the correct layout like in [this screen snapshot](https://user-images.githubusercontent.com/104370511/224515373-2a085134-e8d9-4864-a9e2-02f6f248fb96.png).

I forgot to mention that the Android and/or GTK apps might need to implement the same fix when loading cool.html to get the proper layout for RTL languages.

**Comment by plubius** [comment]
The fix for this bug is now in the latest TestFlight build. Please close if the bug is fixed for you.

Note: "fixed" in this build means that the "Send Feedback" button is not shown in the Help toolbar since there is no feedback URL associated with the iOS app.

**Comment by nikslor** [comment]
Looks good in 22.05.11 (22.5.202303212054); thanks a lot @plubius!
