### ISSUE TITLE
Copy internal link to clipboard doesn't work

### ISSUE THREAD

**Issue by MagsMagnoli** [CollaboraOnline/online#5871]
**Describe the bug**
Clicking 'copy to clipboard' for internal link doesn't work

**To Reproduce**
1. Go to a document
2. Click on sharing > copy to clipboard
3. Paste
4. See link ot copied

**Expected behavior**
Url is pasted

**Actual behavior**
Previous clipboard entry is pasted

**Screenshots**
[Video](https://user-images.githubusercontent.com/4146037/219648526-4c7b4046-850f-4033-98ec-3dea3bc6834d.mov)

<img width="786" alt="Screenshot 2023-02-17 at 06 55 16" src="https://user-images.githubusercontent.com/4146037/219648064-e42df2a9-ce16-4c01-a477-fe04de2cf3d8.png">

**Desktop (please complete the following information)**
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Version: 22

**Comment by pedropintosilva** [comment]
Hello @MagsMagnoli  and thanks for taking the time to report this! I have checked the video and it seems this would be better reported under https://github.com/nextcloud/server since the copy internal link is probably handled there ( https://github.com/nextcloud/server/blob/master/apps/files_sharing/src/components/SharingEntryInternal.vue )

**Comment by pedropintosilva** [comment]
@MagsMagnoli : actually that should be fixed with the next release through https://github.com/nextcloud/server/pull/36450 !

**Comment by MagsMagnoli** [comment]
thanks for the update @pedropintosilva! 🙌
