### ISSUE TITLE
deepl configuration should be available as menu - especially running a collabora  docker 

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/online#5994]
**Is your feature request related to a problem? Please describe.**

https://sdk.collaboraonline.com/docs/deepl_translator.html
describes how to configure deepl translation modifying coolwsd.xml
this file is "in" the docker and should be external to survive docker code updates.
```
<deepl desc="DeepL API settings for translation service">
     <enabled desc="If true, shows translate option as a menu entry in the compact view and as an icon in the tabbed view." type="bool" default="false">true</enabled>
     <api_url desc="URL for the API" type="string" default="">https://api-free.deepl.com/v2/translate</api_url>
     <auth_key desc="Auth Key generated by your account" type="string" default=""></auth_key>
 </deepl>
```
**Describe the solution you'd like**
Api_url and auth_key should be configurable using a setup tool / GUI interface.

**Comment by thebearon** [comment]
Actually, this would be more for the integration to set, it would not make sense to set this in Collabora Online, because that is not persistent (well, it could be saved to browser local storage, but it still isn't truly persistent).

The normal way to do this in case of containers is to specify via `-e "extra_params=..."` when running the container.
These parameters would be something like the following (with `url` and `key` substituted respectively):
`-e "extra_params=--o:deepl.enabled=true --o:deepl.api_url=<url> --o:deepl.auth_key=<key>"`

Other config items that are to be overridden can be added similarly.

**Comment by ferdiga** [comment]
thanks, works
BTW all extra_params must be on ONE line
