### ISSUE TITLE
draft comment lost when switching tabs

### ISSUE THREAD

**Issue by KiaraGrouwstra** [CollaboraOnline/online#5995]
**Describe the bug**
When I start a draft comment in a document, it seems to get lost when switching tabs.

**To Reproduce**
1. open `.odt` document
2. start writing a comment without submitting
3. switch tabs back and forth
4. draft comment vanished

**Expected behavior**
draft comment still there

**Actual behavior**
draft comment vanished

**Desktop (please complete the following information)**
 - OS: arch
 - Browser: firefox
 - Version:
   - Nextcloud: 24
   - Nextcloud Office: 6.3.3
   - Collabora Online - Built-in CODE Server: 22.5.802

**Comment by sebastiaanveld** [comment]
I can duplicate this in the Smoke Test environment (Collabora Staging). But not only switching tabs triggers this, also just clicking like right mouse button on the Windows Taskbar triggers the acceptance of the comment. This issue is only triggered while the sidebar is not visible. When the sidebar is visible for new comments you can happily switch tabs and return to the editor to add test to the still editable comment. Tough when adding follow-up comments on previous comments triggers the auto-accept again when switching tabs or clicking on the Windows taskbar.

Steps to duplicate:
- Open an .odt or .docx for editing
- Make sure the Sidebar is not visible
- Add a New Comment
- Switch tabs in Firefox or click on the Windows taskbar so something pops up (I click Greenshot to get a screenshot triggered)
- The New Comment gets automatically accepted

![image](https://user-images.githubusercontent.com/37268999/224649071-f3cba15d-0a67-4476-a0dc-73ab371efff7.png)


Then:
- Make sure the Sidebar is now made visible
- Add another New Comment to a section in the document

![image](https://user-images.githubusercontent.com/37268999/224649597-92aae7b5-d9d5-4b0f-be36-33268c8d775d.png)

- Switch tabs in Firefox or click on the Windows taskbar so something pops up (I click Greenshot to get a screenshot triggered)
- The New Comment does not get automatically accepted, you can further add text to the previous comment still waiting to be saved

![image](https://user-images.githubusercontent.com/37268999/224649670-677963b1-58da-4787-8c76-7c5e021ca74d.png)

Then:
- Make sure the Sidebar is still visible
- Add a Reply to the previous Comment
- Switch tabs in Firefox or click on the Windows taskbar so something pops up (I click Greenshot to get a screenshot triggered)
- The Reply does get automatically accepted
- 

COOLWSD version: 23.05.0.1 git hash: [f335d08e]
LOKit version: built on Collabora Office 23.05.0.1 git hash: [3130211]
Served by: openSUSE Leap 15.3  [e7a25fcd]
Windows 11, latest patches
Firefox 110.0.1 (x64)

**Comment by Ezinnem** [comment]
I can confirm that the draft is not saved(if the sidebar is closed) when the tabs are switched.

**Comment by gitgt** [comment]
Fixed in 23.05.2.
