### ISSUE TITLE
Rename: document name changes twice

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#6131]
When performing a rename the indication of the process to the user could be clearer. Currently the filename is changed back to the original, some loading happens and then after some time the name changes to the new one.

Ideally there would be a continuous loading indicator in some way and the name should not change back.

https://user-images.githubusercontent.com/3404133/229732793-8de037f1-10ce-471c-9354-09438f3a3b45.mov

**Comment by thebearon** [comment]
CC @pedropintosilva

**Comment by pedropintosilva** [comment]
Thanks @lpranam for taking this

From the screenshare it seems we we have 3 problems to tackle here it seems.

1. No loading
  * I think, and since we are saving the document and create a new one, we could re-use `openBusyPopup`.
  * Good to have: 
    * Would be nice to change that to allow to pass to that additional css class or less generic simply add additional css class for this case in specific. This would help in the case we want to add some customizations for this case 
    * And add another control similar to `spinnerImgControl` maybe name 'spinnerRenameImgControl' where we could change the animation
3. "The name should not change back."
  * I'm not sure what @juliushaertl means by this. But probably that the change in the input field should happen only once.

**Comment by jancborchardt** [comment]
I would even ideally say that there should not even be loading feedback. Renaming is not something that people feel is a heavy action, so having a loading indicator there would make the app feel slow. We can simply fake it and show an error in case there is one?

**Comment by pedropintosilva** [comment]
@jancborchardt ah nice, I would most def. prefer to don't add any indicator

**Comment by pedropintosilva** [comment]
# Input field 

## Current situation

still there is a lot of things going on in the background and this will always take some time, that's why we see : 
1. User changes the name and presses enter
1. Native web browser's behaviour: input field value changes
1. We do the overwriting and then send the RequestedName
1. Input field changes to the current name (still not renamed)
1. Then when we get the document reloaded the input field changes again to the new name

## Proposal

I don't think trying to hack on the `2.` is smart. Probably best would be to (thinking out loud here):

### In the transient state: replace it with text
After the `1.` to: make the input field disabled (attribute); replace its contents with `Renaming…` until we get back the response so we can change back to enabled input with new name, 

There are other complex alternatives that I can think of: replace the input field with some CSS animation (3 dots fade in sequentially etc) but I think we should aim for a first step that is easily done in short time so we can they iterate upon.

# Document

I don't think these things are critical and I don't think we need to worry do much about this but here it goes so I don;t forget.

I also note that would be nice:
* to don't see the username showing up on the left top side
* to avoid seeing comments disappear and then appear again (they disappear before the first document is unload and appear after the new renamed document appears. Instead would be nice if these things were happening at the same time at least visually)

**Comment by pedropintosilva** [comment]
Thanks Pranam. @lpranam 's fix does exactly that
