### ISSUE TITLE
Hyperlink dialog layout regression

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6288]
**Describe the bug**
![image](https://user-images.githubusercontent.com/65948705/236454734-2a25f40a-30a2-4f95-a78d-dcdcc1aeb9b7.png)

**To Reproduce**
1. Select Text
2. insert hyperlink (or ctrl+k)
3. See how the elements are misplaced

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva  this issue is related to firefox browser as

width : --webkit-fill-available
this property will be skip in Firefox  browser and eventually will take width: auto.

 **CSS will skip over style declarations it doesn't understand. Mozilla-based browsers will not understand -webkit-prefixed declarations, and WebKit-based browsers will not understand -moz-prefixed declarations.**

**Comment by Darshan-upadhyay1110** [comment]
`.jsdialog.ui-edit, #hyperlink-text-box:not(.mobile-wizard) {
	color: var(--color-text-dark);
	background-color: var(--color-background-dark);
	line-height: 28px;
	max-height: 32px;
	width: auto;
	min-width: -moz-available;
	min-width: -webkit-fill-available;
	border: 1px solid var(--color-border-dark);
	border-radius: var(--border-radius);
	overflow: hidden;
}
`
change jsdialogs.css as this way we will get same behaviour as  other browser

**Comment by pedropintosilva** [comment]
nice so , feel free to push your first Pr ;)

**Comment by Darshan-upadhyay1110** [comment]
i am on it , thanks :)
