### ISSUE TITLE
writer comment performance ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#6440]
Writer takes a performance hit when there are large numbers of comments around both on and off the visible screen. I have a vague recollection from previous profiling that we are creating a huge number of vcl windows, and doing the PC-style comment layout in an (ultimately invisible) side-bar that is never seen or rendered by the tiled rendering =)

I would expect that cutting that nonsense out would be some rather low-hanging fruit - my understanding is that commenting is all done on the client side in JS and the layout is done by reference to anchor positions / selections in the document in JS - but I may be wrong; worth checking.

Thanks @caolanm =)

**Comment by caolanm** [comment]
I think we got this one with https://gerrit.libreoffice.org/c/core/+/155453 which skips figuring out where the windows and widgets should go when there are not shown, which is the case for online. We did still need to know where the comment *anchor* is when things move around because that's where we draw the comment indicator (or line to it from comment IIRC) in online, but the comment widget itself calc, overlapping etc. should be no more.
