### ISSUE TITLE
Selected or cursor paragraph doesn't change color while switching to dark mode.

### ISSUE THREAD

**Issue by codewithvk** [CollaboraOnline/online#6459]
**Describe the bug:**
When a section of a paragraph is selected and the user switches to dark mode, the font color of the selected text does not change. The user has to click outside the selected area to see the actual color.

**To Reproduce:**

Go to Impress (or any applicable tool).
Ensure that you are in light mode. If not, switch to light mode.
Start editing some text without clicking elsewhere. The cursor should be in writing mode.
Switch to dark mode by navigating to View -> Dark mode.

**Video Demo**

https://github.com/CollaboraOnline/online/assets/61119120/80298b34-b487-4b17-ab1f-77a875ba927b

**Additional context**
I would like to work on this issue :)

**Comment by pedropintosilva** [comment]
Hi @codewithvk and thanks for reporting. 

Probably that textbox has #000 text in it while the other has text set with `automatic` color and that's why one changes and the other doesn't. Can you confirm this?

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva i have schecked this issue. A i am seeing when issue is not related because of automatic color. 

When we change the mode from light toi dark and if at that time any of the text area is active or selected then only that part is not ( text ) is not getting refreshed . 

and then if we put cursor away from that text box or just take focus away that SVG will update after focus changes.

@codewithvk correct me if i am missing here anything to describe.

**Comment by codewithvk** [comment]
@Darshan-upadhyay1110 Correct, We have to set the dynamic color of a canvas when the cursor selected text. I think we can do using `context.fillStyle= --Dynemic-CSS-Variable-of-color` when the cursor is active.

Would love hear from you @pedropintosilva

**Comment by pedropintosilva** [comment]
Cool! I have assigned you @codewithvk

**Comment by codewithvk** [comment]
> @Darshan-upadhyay1110 Correct, We have to set the dynamic color of a canvas when the cursor selected text. I think we can do using `context.fillStyle= --Dynemic-CSS-Variable-of-color` when the cursor is active.
> 
> Would love to hear from you @pedropintosilva

This approach won't work as I was think. Any hint @Rash419 !
