### ISSUE TITLE
No way to set automatic text color for dark mode compatibility

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#6508]
When testing the dark mode a bit with @jancborchardt we noticed that some documents may only show black text in dark mode. This might of course be the documents fault and I'm unsure if there can be some automatic detection. However when trying to manually set the color, there are only the options black and white as actual colors which would not work then when switching between modes.

There seems to be a way to set automatic color in libreoffice, which is not available in online, but probably worth adding for making the dark mode more usable

![image](https://github.com/CollaboraOnline/online/assets/3404133/e7a265ac-fc69-4bff-a9b3-c1fb4950d761)

cc @pedropintosilva since we briefly talked about that as well

**Comment by thebearon** [comment]
I'm not sure how much the widgets can be customized, the background color one has an item that could perhaps be used here as well.

Also, there's an issue with the handling of default templates that black is used as font color instead of automatic (probably not the fault of template files, but how they're handled).

**Comment by gitgt** [comment]
There are #6537 and #6546 that should fix this. I think that this one may be closed. If you think that something is missing, please comment or reopen.
