### ISSUE TITLE
Mobile: buttons with text color discrepancies

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7141]
### Describe the Bug

Open mobilewizard and notice that button are being styled rather oddly :
![image](https://github.com/CollaboraOnline/online/assets/65948705/509ade73-f61d-4d2f-85b7-82d410816af8)

This seems to do with the accessKeys spilling to mobile which might not be useful here:
```html
<button class="ui-pushbutton mobile-wizard" id="ok" accesskey="O" tabindex="0">
    <u class="access-key">O</u>K
</button>
```

### Expected Behavior

 - [ ] Make sure that `#mobile-wizard button u` is set with the same color as we are setting `#mobile-wizard button`
 - [ ] Maybe we could rethink if we should allow these sub-elements to be generated for mobile

**Comment by Darshan-upadhyay1110** [comment]
there are two solutions i am seeing here 
 - Simple solution which would be to add a css for `<u>` inside #mobile-wizard-button. but i am seeing this as a temporary solution.
 - proper fix would be to check if we need this <u> tag for acces key ( because some of the structrure changed here for acces keys. not sure of this need @gokaysatir's view here 
  - and if this element not needed any more then just remove that element generation thing and all willl be fixed.
  
  
  CC: @gokaysatir
