### ISSUE TITLE
Format Cell broken with custom text

### ISSUE THREAD

**Issue by relikd** [CollaboraOnline/online#7196]
### Describe the Bug

Format Cell does not update cell if using static text in format. I knew this worked before, because my spreadsheet has some cells that were formatted with Collabora. Further, it also works if I reuse a previous Cell Format from the format history list. But as soon as I try to change the text, it will ignore my input and revert to the previous value.

### Steps to Reproduce

1. Enter a number in a new cell
2. Click on 'Format Cell'
3. Set new format to be `#" suffix"`

### Expected Behavior

The cell should now print "12 suffix"

### Actual Behavior

The cell is either malformed or does not update at all.

### Screenshots

https://github.com/CollaboraOnline/online/assets/1321720/a0807dc0-05b8-476e-9ed3-30d07e1c153a

### Desktop

 - **Device:** macOS
 - **Browser:** Firefox 116
 - **Version:** collabora/code:23.05.3.1.1

### Additional Context

N/A

**Comment by Tex2002ans** [comment]
I can reproduce in:

> COOLWSD version: 23.05.3.1 (git hash: 0621aa48)
> LOKit version: Collabora Office 23.05.3.1 (git hash: aaeaa1f)
> Served by: Linux Mint 21.1
> Server ID: 7ace7a16

- - -

In LibreOffice 7.6.0:

- Step 4, you type: `#" suffix"`.
- Press OK.
- Right-Click > Format Cells
- Still see `#" suffix"` in "Format-Code" box.

In Collabora Online, you get:

- Step 4, you type: `#" suffix"`.
- Press OK.
- Right-Click > Format Cells
- Still see `#" suffix` in "Format-Code" box.
   - Notice the missing quote at the end!

So it looks like that Collabora version of the box might be doing extra parsing on the string and getting confused with the quotation marks (?).

- - -

**Side Note:** While testing this after Step 4, I also got a random crash.

Here is the log + backtrace:

<details>
<pre>
warn:editeng:3296:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3296:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3296:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3296:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3296:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:vcl:3296:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3296:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:legacy.osl:3296:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3296:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3296:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:editeng:3331:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3331:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3331:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3331:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3331:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:vcl:3331:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3331:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:legacy.osl:3331:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3331:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3331:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:editeng:3378:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3378:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3378:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3378:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3378:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:vcl:3378:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3378:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:legacy.osl:3378:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3378:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3378:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:editeng:3418:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3418:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3418:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3418:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3418:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:vcl:3418:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3418:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:legacy.osl:3418:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3418:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3418:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:editeng:3465:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3465:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3465:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3465:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3465:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:vcl:3465:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3465:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:legacy.osl:3465:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3465:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3465:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:editeng:3504:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3504:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3504:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3504:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3504:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:vcl:3504:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3504:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:legacy.osl:3504:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3504:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:3504:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:editeng:3549:3289:editeng/source/misc/acorrcfg.cxx:108: Unable to iterate directory. com.sun.star.ucb.InteractiveAugmentedIOException message: "an error occurred during file opening" Code: 22
warn:vcl:3549:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:3549:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:vcl:3549:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3549:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
coolwsd: wsd/ClientSession.cpp:661: virtual bool ClientSession::_handleInput(const char*, int): Assertion `UnitWSD::isUnitTesting() ? true : getCanonicalViewId() != 0 && getCanonicalViewId() >= 1000' failed.
wsd-03254-04198 2023-09-06 20:13:30.231620 -0400 [ docbroker_007 ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x3e800000cb6
Recent activity:

Backtrace 3254 - wsd 23.05.3.1 0621aa482:
./coolwsd(_ZN7SigUtil13dumpBacktraceEv+0x7f)[0x562b0aaa09ef]
./coolwsd(+0x287db5)[0x562b0aaa0db5]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f399e97d520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f399e9d1a7c]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f399e97d476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f399e9637f3]
/lib/x86_64-linux-gnu/libc.so.6(+0x2871b)[0x7f399e96371b]
/lib/x86_64-linux-gnu/libc.so.6(+0x39e96)[0x7f399e974e96]
./coolwsd(_ZN13ClientSession12_handleInputEPKci+0x2914)[0x562b0a9fa6f4]
./coolwsd(_ZN7Session13handleMessageERKSt6vectorIcSaIcEE+0x58)[0x562b0aa90858]
./coolwsd(_ZN16WebSocketHandler15handleTCPStreamERKSt10shared_ptrI12StreamSocketE+0x320)[0x562b0a8da310]
./coolwsd(_ZN16WebSocketHandler21handleIncomingMessageER17SocketDisposition+0x9b)[0x562b0a8dc90b]
./coolwsd(_ZN12StreamSocket10handlePollER17SocketDispositionNSt6chrono10time_pointINS2_3_V212steady_clockENS2_8durationIlSt5ratioILl1ELl1000000000EEEEEEi+0xea)[0x562b0a99989a]
./coolwsd(_ZN10SocketPoll4pollEl+0x56f)[0x562b0aae43cf]
./coolwsd(_ZN14DocumentBroker10pollThreadEv+0xd59)[0x562b0a93e969]
./coolwsd(_ZN10SocketPoll18pollingThreadEntryEv+0xe5)[0x562b0aae65a5]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253)[0x7f399ed48253]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7f399e9cfb43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7f399ea61a00]

ERROR: Fatal signal! Attach debugger with:
sudo gdb --pid=3254
 or 
sudo gdb --q --n --ex 'thread apply all backtrace full' --batch --pid=3254
Sleeping 60s to allow debugging: attach 3254
warn:vcl:3549:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_stylespreview.png at 1
warn:vcl:3549:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_stylespreview.png
warn:sc:4199:3289:sc/source/core/tool/addincol.cxx:303: Failed to initialize create instance of sheet.AddIn
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:vcl:4199:3289:vcl/source/window/floatwin.cxx:66: FloatWindow::FloatingWindow(): - pParent == NULL!
warn:vcl:4199:3289:vcl/source/window/floatwin.cxx:71: FloatWindow::FloatingWindow(): - pParent == NULL and no AppWindow exists
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:legacy.osl:4199:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:4199:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:4199:3289:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 25917
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26189
warn:sfx.control:4199:3289:sfx2/source/control/dispatch.cxx:1211: Childwindow slot missing: 26190
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_formatstylesmenu.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_formatstylesmenu.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_formatsparklinemenu.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_formatsparklinemenu.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_currentconditionalformatdialog.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_currentconditionalformatdialog.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_insertsparkline.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_insertsparkline.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_deletesparkline.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_deletesparkline.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_deletesparklinegroup.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_deletesparklinegroup.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_editsparklinegroup.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_editsparklinegroup.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_editsparkline.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_editsparkline.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_groupsparklines.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_groupsparklines.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_ungroupsparklines.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_ungroupsparklines.png
warn:vcl.fonts:4199:3289:vcl/unx/generic/fontmanager/fontconfig.cxx:938: In glyph fallback throwing away the language property of en because the detected script for '0x9f3' is Bengali and that language doesn't make sense. Autodetecting instead.
warn:vcl.builder:4199:3289:vcl/source/window/builder.cxx:1614: we should have no placeholders for tabpages
warn:vcl.builder:4199:3289:vcl/source/window/builder.cxx:1614: we should have no placeholders for tabpages
warn:vcl.builder:4199:3289:vcl/source/window/builder.cxx:1614: we should have no placeholders for tabpages
warn:svtools.misc:4199:3289:svtools/source/misc/langtab.cxx:241: Language: 0x540a with unknown name, so returning generated: Spanish (United States) {es-US}
warn:svtools.misc:4199:3289:svtools/source/misc/langtab.cxx:241: Language: 0x8403 with unknown name, so returning generated: Catalan (Andorra) {ca-AD}
warn:svtools.misc:4199:3289:svtools/source/misc/langtab.cxx:241: Language: 0x840a with unknown name, so returning generated: Spanish (Equatorial Guinea) {es-GQ}
warn:svtools.misc:4199:3289:svtools/source/misc/langtab.cxx:241: Language: 0x8803 with unknown name, so returning generated: Catalan (France) {ca-FR}
warn:svtools.misc:4199:3289:svtools/source/misc/langtab.cxx:241: Language: 0x880a with unknown name, so returning generated: Spanish (Philippines) {es-PH}
warn:svtools.misc:4199:3289:svtools/source/misc/langtab.cxx:241: Language: 0x8c03 with unknown name, so returning generated: Catalan (Italy) {ca-IT}
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:legacy.osl:4199:3289:svx/source/svdraw/svdpagv.cxx:306: SdrPageView::DrawLayer: Creating temporary SdrPageWindow (ObjectContact), this should never be needed (!)
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_formatstylesmenu.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_formatstylesmenu.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_formatsparklinemenu.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_formatsparklinemenu.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_currentconditionalformatdialog.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_currentconditionalformatdialog.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_insertsparkline.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_insertsparkline.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_deletesparkline.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_deletesparkline.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_deletesparklinegroup.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_deletesparklinegroup.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_editsparklinegroup.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_editsparklinegroup.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_editsparkline.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_editsparkline.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_groupsparklines.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_groupsparklines.png
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:92: Failed to load scaled image from cmd/sc_ungroupsparklines.png at 1
warn:vcl:4199:3289:vcl/source/image/ImplImage.cxx:116: Failed to load stock icon cmd/sc_ungroupsparklines.png
warn:vcl.builder:4199:3289:vcl/source/window/builder.cxx:1614: we should have no placeholders for tabpages
warn:vcl.builder:4199:3289:vcl/source/window/builder.cxx:1614: we should have no placeholders for tabpages
warn:vcl.builder:4199:3289:vcl/source/window/builder.cxx:1614: we should have no placeholders for tabpages
Finished sleeping to allow debugging of: 3254
Parent process has died. Will exit now. (0: Success)
frk-03289-03289 2023-09-06 20:14:30.935994 -0400 [ forkit ] TST  UnitBase [uninit] (+0ms): Uninitializing unit-tests: SUCCESS| common/Unit.cpp:347
frk-03289-03289 2023-09-06 20:14:30.936028 -0400 [ forkit ] TST  UnitKit [~UnitBase] (+0ms): UnitKit: ~UnitBase: SUCCESS| common/Unit.cpp:407
warn:sfx.appl:4199:3289:sfx2/source/appl/app.cxx:166: Memory leak: some object shells were not removed!
warn:legacy.tools:4199:3289:sfx2/source/appl/appquit.cxx:59: existing SfxViewFrame after Execute
warn:legacy.tools:4199:3289:sfx2/source/appl/appquit.cxx:60: existing SfxObjectShell after Execute
warn:legacy.tools:4199:3289:sfx2/source/appl/appquit.cxx:74: active foreign ViewFrame
make: *** [Makefile:6932: run] Aborted (core dumped)
</pre>
</details>

I'm unsure exactly what I did:

- After Step 4, I had a cell with the broken `#" suffix`
- I then Right-Clicked and retyped `#" suffix"` again.
- Pressed OK.
- I was then typing info into this Github, when I returned, Collabora Online was crashed.

**Comment by relikd** [comment]
A month has passed ... any news on a fix?

**Comment by timur-g** [comment]
@relikd " knew this worked before, " Do you know in which version?

Note: please do not ask "any news, when fix" - as it does not help, this is community board with no timeline, if you need timed fixes there is commercial support, paying which really makes all those fixes possible.

**Comment by relikd** [comment]
Just installed 22.05.14.3.1 and there it works

**Comment by timur-g** [comment]
Already wrong in old [bcf1f0fb](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/bcf1f0fb'));), so all 23.05 is NOK, seems JS dialog issue. 22.05 is OK.

**Comment by timur-g** [comment]
Thanks, to be in 23.05.5.2.
