### ISSUE TITLE
Android Mobile: Pinch-zoom can displace sheet area

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#7275]
### Describe the Bug

Pinch Zoom affects the dimensions of the Column and Row.

### Steps to Reproduce

1. Open a Calc file in Android.
2. Using fingers, Zoom out and Scroll up/down

Notice that the Column/Row width is displaced
### Expected Behavior

The zoom does not cause area displacement.

### Actual Behavior

The zoom does cause area displacement.

### Screenshots

https://github.com/CollaboraOnline/online/assets/54344301/c7ab8adb-5c3d-4824-b730-184dd2eb1ed8

### Smartphone

(Please complete the following information)
 - **Device:**Samsung A13
 - **OS:** Andriod 13
 - **Version:** 23.05

**Comment by timur-g** [comment]
@Ezinnem please add screencast.

**Comment by frederikb96** [comment]
Hi, thanks for creating this bug. I would like to add that not only a displacement is happening but that scrolling or pinching is not usable since the interface is not responsive.

# Screen record

- I am opening a normal spread sheet with only a few entries
  - I am trying to scroll and pinch, but very laggy and no reaction at all for a long time
  - I enabled the developer pointer location to show that I am actually doing scroll and pinch movements
- Afterwards, I open a presentation and here it is much better
  - A bit laggy, but that is totally fine, scrolling and pinching works

https://github.com/CollaboraOnline/online/assets/83548283/c9d983cd-f4c3-47a6-b3e3-dcf849375d86

# Hardware Setup
- I am running Nextcloud AIO with Nextcloud Office (so default setup without any changes from my side) on a Server with 32 GB of RAM and 8 cores. No high CPU usage or RAM consumption.
  - Latest stable Nextcloud AIO version and Office Version
- I tested it on multiple phones, the video is from a Fairphone 4 with 6 GB of RAM
  - No lags normally on this phone, all very smooth

**Comment by Rash419** [comment]
> Hi, thanks for creating this bug. I would like to add that not only a displacement is happening but that scrolling or pinching is not usable since the interface is not responsive.
> 
> # Screen record
> * I am opening a normal spread sheet with only a few entries
>   
>   * I am trying to scroll and pinch, but very laggy and no reaction at all for a long time
>   * I enabled the developer pointer location to show that I am actually doing scroll and pinch movements
> * Afterwards, I open a presentation and here it is much better
>   
>   * A bit laggy, but that is totally fine, scrolling and pinching works
> 
>  screen-recorder-unlimited-2023-10-19-09-45-55.mp4 
> # Hardware Setup
> * I am running Nextcloud AIO with Nextcloud Office (so default setup without any changes from my side) on a Server with 32 GB of RAM and 8 cores. No high CPU usage or RAM consumption.
>   
>   * Latest stable Nextcloud AIO version and Office Version
> * I tested it on multiple phones, the video is from a Fairphone 4 with 6 GB of RAM
>   
>   * No lags normally on this phone, all very smooth

There has been fixes for scrolling and perfomance in latest version. which CODE version are you running

**Comment by frederikb96** [comment]
Ah ok, yes might be fixed then. I am running:
23.05.4.2
This is the latest for Nextcloud AIO. But I just checked and 23.05.5 will come soon for Nextcloud AIO since its already part of the beta release :)

**Comment by mjji** [comment]
laggy reaction to freezing when scrolling spreadsheet in calc on android is still there in 23.05.5.2, testes with samsung s7 and s7+ tablets.

**Comment by Ezinnem** [comment]
I can confirm that the pinch-zoom issue in the Andriod mobile device has been fixed.

@mjji please can you create an issue with the details or screen recording showing this laggy reaction via the link https://github.com/CollaboraOnline/online/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md
