### ISSUE TITLE
Improve 'Following' UI

### ISSUE THREAD

**Issue by Minion3665** [CollaboraOnline/online#7602]
### Is your feature request related to a problem?

Here are 3 users in a document
![3 users in a document](https://github.com/CollaboraOnline/online/assets/34243578/c79f04c8-efdd-40e7-a837-75fbd28ad033)

Here's what it looks like when I follow one of them
![it looks like the same screenshot, but I followed one of them- I promise...](https://github.com/CollaboraOnline/online/assets/34243578/fd92d663-43fc-4bf4-a294-4661cfe6d1e0)

The only way I can see which one I followed is by clicking on users again
![a close-up of the users popup, showing I'm following LocalUser#3](https://github.com/CollaboraOnline/online/assets/34243578/60635ad7-2f2d-4bae-b8f0-69cb3995c42d)

This problem is exacerbated when using the always follow the editor feature
![a closeup of the always follow the editor checkbox](https://github.com/CollaboraOnline/online/assets/34243578/c2910c08-4da2-4908-82f8-130c7c75d436)

Because then there's not a good way to know who you jumped to beyond looking who's editing nearby
![a screenshot of the users popup, showing no "following" text](https://github.com/CollaboraOnline/online/assets/34243578/0b8b2e00-9f1c-4b26-8ce3-e317b1256858)

### Describe the solution you'd like

Other apps, (example: Figma) do this way better: look at this, it's clear who I'm following right from the top corner, not to mention the document border
![a screenshot of figma, showing off its awesome following UI](https://github.com/CollaboraOnline/online/assets/34243578/8154e47f-e0a2-437b-a13b-86a545ab858f)

No matter who you're following, they go right to the top of the list... it's beautiful!
![image](https://github.com/CollaboraOnline/online/assets/34243578/8bcfac07-0091-40ef-ac17-746c41bd1573)

### Describe any other solutions you've considered

I imagine an easier (although worse) solution would be something that just showed you were following someone, even that isn't clear currently without clicking on users 

### Additional context

Figma doesn't stand alone, VSCode also does something similar

![vscode, showing a "following" banner and a green pin to show you're following someone](https://github.com/CollaboraOnline/online/assets/34243578/89b8b0fa-6d5d-45e0-af82-bf3ea6a2c5b7)
![a closeup of the green pin](https://github.com/CollaboraOnline/online/assets/34243578/5c621956-db95-4422-b755-7fa768449f8e)
![a closeup of the following banner](https://github.com/CollaboraOnline/online/assets/34243578/1e51e56d-afb2-422e-b244-eeae06c75b8d)

**Comment by pedropintosilva** [comment]
Thanks for reporting this! 
I think we have discuss this long time ago in multiple community calls and also maybe there is something here on GH https://github.com/CollaboraOnline/online/issues/4920 (but it looks very unorganized : /) so I'm very pleased that this got file : )

I think would be nice to check what other Office suites or text editors are doing (MSO , Apple, G) But also collaborative note taking apps such dropbox Paper, notion, evernte, etc. This is just we grab as much context possible before spinning our wheels thinking or doing some "new".

Or if we are looking at figma would be nice to see what the others do (penpot, sketch, adobe, etC)

Nevertheless there are already nice points here. Let me try to divide them into sections.

# Users indicator

What: The avatars at the top that trigger the user list

> Other apps, (example: Figma) do this way better: look at this, it's clear who I'm following right from the top corner
> ![image](https://github.com/CollaboraOnline/online/assets/65948705/1ef72224-ae45-47bd-bde5-ba03913e6c16)

To be it doesn't look that clear. Sure there is a circle with pink neon but what all those 3 circles do different between each  other and what happens when there are multiple (more than 3) different users?

Wouldn't be a nice iterative step  to simply shift the order of the avatars and maybe set opacity to all the other ones?
* We currently have the avatars stacked (each one shows partially) and that gets more stacked depending on the number of users until it reaches a limit
* 
![image](https://github.com/CollaboraOnline/online/assets/65948705/0213cb6f-3d63-43cf-8778-535e2597cc19)

* We could just reorder them, so the person who we are following is up top
* Additional we could think about other thing to emphasize that we are in "following mode"
  * Play with opacity , so the rest of the avatars are dimmed 

# User list pop up

What: The  pop up that opens when clicking i the Users indicator (avatars)

>  ![image](https://github.com/CollaboraOnline/online/assets/65948705/bcfa6d51-45c4-4b46-a3e3-d44623cadf89)

I don't understand if I'm following the yellow or the pink or what is the spotlight

Currently we have 
![image](https://github.com/CollaboraOnline/online/assets/65948705/b2d8eafd-ee1a-4d39-9f44-17a420268b18)

and if we don't we should do it.

I think that is ok until... we reach the "Follow the editor" functionality. Then no one understand who we are following (we only the cursor in the document)
* Should we also apply the same behaviour as discussed before or will the switching avatar order will be annoying and a constant?
  * And what about doing that plus show an indicator that we are in Follow the editor mode?

# Document

## Page
> not to mention the document border
> ![image](https://github.com/CollaboraOnline/online/assets/65948705/f9bfd24c-830f-4595-8aa4-459cfe12912a)

Good idea. True that can really show at glance that I'm following someone. Of course since we are in the formatting/ DTP realm people can start to complain that their documents now have a glitch where the page border changes colors :thinking: But maybe depending on how we do it we can avoid those Or...

## Page's content

>  Figma doesn't stand alone, VSCode also does something similar
> ![image](https://github.com/CollaboraOnline/online/assets/65948705/49b6fa5f-c3f0-423a-871f-2df2384ea980)

I think that is nice in the VSCode but I fail to see it in Collabora Online or at least without causing clutter (documents with tables, images etc and how that overlay will be displayed 

Wouldn't it help if we for now just made sure that the person that I'm following has always the cursor name visible? 

# Document surrounding

* The border could also be made it a bit separated from the document.
* We could also add a Marker on the side (outside of the document) that shows the "Following user 2"

**Comment by Minion3665** [comment]
> I think would be nice to check what other Office suites or text editors are doing (MSO , Apple, G)

I didn't find following features in Google when I checked, I remember MS having very poor collaboration from my time @hrsfc/students but we can test again

> But also collaborative note taking apps such dropbox Paper, notion, evernte, etc

I agree, it'd be very nice to see what things like notion do

> Or if we are looking at figma would be nice to see what the others do (penpot, sketch, adobe, etC)

In my mind, Figma being a graphical design app wasn't the relevant part, it was it being collaborative and having a particularly nice (in my opinion) following experience... imo we should look particularly hard at collaborative software rather than at graphical design software

> To be it doesn't look that clear. Sure there is a circle with pink neon but what all those 3 circles do different between each other

the 3 circles here are 3 "different" users (in reality it's me in 3 different browser tabs)... I think it's partially that my screenshots don't illustrate it particularly clearly, it's extremely nice and clear to use... apologies

> what happens when there are multiple (more than 3) different users?

As I remember, Figma doesn't keep adding users... I think it stacks them after a while

> I don't understand if I'm following the yellow or the pink or what is the spotlight

Ahh, sorry, in this screenshot I was hovering over the pink one... the colored circle in Figma always means "this is the one you're following", and it also displays in the border of the page (you can see a little of the border in that screenshot, but the one you've put later illustrates it more clearly)

> I think that is nice in the VSCode but I fail to see it in Collabora Online or at least without causing clutter (documents with tables, images etc and how that overlay will be displayed

You're right, I think this is less a "we should do this" and more a "there are different ways to display the same information"... I really like Figma's way of doing it, but I don't think everything they do would fit in Collabora Online

**Comment by pedropintosilva** [comment]
> particularly nice (in my opinion) following experience... imo we should look particularly hard at collaborative software rather than at graphical design software

exactly my initial thoughts. And personally I don't find figma particularly good at that if I'm being honest.
