### ISSUE TITLE
Last modification in statusbar instead of menubar area

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#787]
I don't know why the Last modification label is next to the menubar. 

From my point of view it should be somewhere in the statusbar, cause Last modification is kind of status information.

In addition it make the editiong UI busy without a benefit.

![2020-11-26 14_54_56-Nextcloud](https://user-images.githubusercontent.com/8517736/100359302-a49b4980-2ff7-11eb-831d-90ea4884a226.png)

**Comment by thebearon** [comment]
In an online solution knowing when your edits were last saved to server is actually a very important piece of information. I've seen similar positioning of this detail in other online services. @pedropintosilva, what do you think?

**Comment by Andreas-Kainz** [comment]
yes it's good to know but if the string is

`Last modification: Nov 26.2020 12:09PM `

I think it's a bit to much.

In addition if you move the string to the very right area it separate the menubar with the modification and wouldn't be that much in the focus.

**Comment by Andreas-Kainz** [comment]
anyhow as Notebookbar didn't show the modification string, I would suggest to have it in the statusbar cause than you see the string in notebookbar and classic view.

**Comment by pedropintosilva** [comment]
Great stuff.
A lot of topics and I think it’s important to clarify and discuss them point by point:

1. why `Last modified` is next tot he menubar?
2. I want to change it to status-bar
3. I think the current time format is too long
4. Notebookbar is missing `Last modified`
5. We should have `Last modified` in both modes and with the same placing

------

- Many labels are somewhat related to status of the document/application but place them all together could be quite confusing for the user
- Why should the Last modified component be re-placed and what problem it solves?

------

1. & 2.

> From my point of view it should be somewhere in the status-bar, cause Last modification is kind of status information.

the Last modified component is placed there for a couple of reasons
- as @thebearon mentioned it is a very important piece for the user and should be visisble at a glance as a **top level** (not really regarding the document’s content but higher, regarding its identification) piece of information 
- so it neighbours the main actions (which are in the top toolbar) because it is indeed a main action **not just a status label** and it can be used in slightly different ways from the integrator side (**revision history**)
- to be adjacent to what is known for the user as the document identifier (**document name**) since normally when users scan for these type of elements they more often than not will look there because..ˇ
- of the importance of **well known** user patterns for users. Something that they expect and thus the learning curve doesn’t skyrocket 
- Collabora Online should integrate well with File Storage Services (FSS) and this should be accounted for. So in here actions from FSS related to the file are always **up top** (above CO) making yet again the case for the current placing.

------

3.
The time format is not fixed. It is possible to be changed by the FSS (disabled) and also can be different depending on the **locale** and its date/time format. Nevertheless and if you think it can be improved that's great! Please feel free to comment bellow with examples and/or mockup.

------

4. 5.
Yes, that’s the goal : ) we need to add the `Last modified` component to the Notebookbar. Would you be interested in working on that ; ) ?

**Comment by Andreas-Kainz** [comment]
I think it should be inline with issue #788 so there should be a general approach for show filename and modification in classic and notebookbar layout.

**Comment by Andreas-Kainz** [comment]
![2020-11-27 11_02_33-Readme md - Nextcloud](https://user-images.githubusercontent.com/8517736/100436864-3c547280-30a0-11eb-8fac-180aa586bc1e.png)

In the markdown editor last modified was arranged on the very right area which I would also prefer and there is only 3 Minutes no last modified: ...

**Comment by Andreas-Kainz** [comment]
When you have on the right the save icon and the 3 minutes ago, ... string it's clear that the string is related to saving in addition the save icon show an red symbol that something is not saved.

![COOL-Header](https://user-images.githubusercontent.com/8517736/100482616-51f58680-30f8-11eb-86e4-a6a48e751dc3.png)

I think it's very useful to have the filename (like it is in google docs and nextcloud markdown editor, ...) more about general COOL layout stuff I add to #55

**Comment by Andreas-Kainz** [comment]
Last modification date should be at top right in the header area like it is in classic bar also for notebookbar.
