### ISSUE TITLE
Print Button in Toolbar should be pdf command

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#789]
The print button in the classic toolbar should be at least an pdf symbol or removed from the classic toolbar.

The reason is:
- it download your file as pdf -> so it should be a pdf symbol

It didn't work
- it didn't use the correct filename or at least the file extension (.pdf) -> so it should be removed cause it didn't work propper. User download a file called `Iundks6R0befVI6OiocSzpMSE6eFuOnB41mO8nEcEiCHEkB7bkzu2vaol6cF3HQM` 
- If you go to File -> Export -> PDF you download the .pdf with the correct filename.

So please use the PDF uno command in the toolbar or remove the command complete.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva

**Comment by kendy** [comment]
@Andreas-Kainz: Thanks for the report! :-) I think it is not this easy, in the browsers that support that, this indeed leads to a print dialog & direct printing, only the browsers that don't support that will only offer a PDF download...

**Comment by Andreas-Kainz** [comment]
Ah ok I used Firefox, but if it didn't offer a real print dialogue it should offer a PDF with correct file name and with the correct extension.

**Comment by pedropintosilva** [comment]
@Andreas-Kainz hm interesting, I tested using also Firefox and it:
- Opened the bult-in PDF preview from FF with actions available such as: Print and download
- If I press print it opens the print dialog and I can print
- If I press the download button it downloads under the name `document.pdf`

**Comment by Andreas-Kainz** [comment]
I checked again. I define in firefox that I'd like to download an pdf automatic so no built-in PDF viewer was used and than the fileneme is cryptic.

**Comment by pedropintosilva** [comment]
oh I see, and it also happens in Chrome if you press print and then print to file it will be with that cryptic name, nut I wonder if it's really possible to change that as I think _Im' not sure_ that CO triggers the print action in the browser which should open a dialog so the user can print. And then I wonder who goes through the hassle of multiple clicks to download via print* instead of just pressing the download icon directly.

Anyhow I think this should maybe be classified as `enhancement` and change the title for something else (more related to this particular issue). What do you think @Andreas-Kainz ?


-----

`* well probably the user that wants to change the options (pages, size) before downloading but that, I think, is not the norm`

**Comment by Andreas-Kainz** [comment]
> 
> And then I wonder who goes through the hassle of multiple clicks to download via print* instead of just pressing the download icon directly.

classic layout has the print button in the toolbar

**Comment by pedropintosilva** [comment]
Right now we are basically triggering the browser's print dialog & direct printing but some browsers (that do not have that feature) use instead a PDF viewer download/print. So for now I will be closing this issue.
