### ISSUE TITLE
localization about chinese-simple（zh-cn） and chinese-Traditional （zh-tw）

### ISSUE THREAD

**Issue by pandagxnu** [CollaboraOnline/online#9730]
### Describe the Bug
The match of User interface localization is not suitable.

### Steps to Reproduce

1. apt install collaboraofficebasis-zh-cn   collaboraofficebasis-zh-tw
2. wopiUrl with "&lang=zh-cn"
3. open webbrowser
4. User interface language is Chinese-simple , but styles ( like 'Title' 'Heading' etc ) is still English.

![1](https://github.com/user-attachments/assets/d2910cfe-4a85-4c77-b640-f3154ce9f13a)

6. wopiUrl with "&lang=zh-tw"
7. User interface language is Chinese-traditional, but styles ( like 'Title' 'Heading' etc ) is Chinese-simple.
![2](https://github.com/user-attachments/assets/c249d0b7-191f-4737-ada0-6d5ad6a7c935)

8. After the following operations，and wopiUrl with "&lang=zh-tw" ，I got expected user interface。

\#  cd /opt/collaboraoffice/program/resource
\#  cp -r zh_TW/ zh_CN
\#  systemctl restart coolwsd.service
![3](https://github.com/user-attachments/assets/0e59ca70-cdc0-4c19-80fe-417cd9673b31)

### version
 - **COOLWSD version:** [24.04.5.2]
 - **Collabora version:** [Collabora Office 24.04.6.1]
 - **OS and version:** [Debian GNU/Linux 12 (bookworm)]

**Comment by timar** [comment]
In the zh-CN case I see in the log:
`warn:lok:34566:33687:sfx2/source/view/lokhelper.cxx:203: LANGUAGE mismatch at setView! ... old (wrong) lang:zh-CN new lang:en-US`
In the zh-TW case I do not see such message and I cannot confirm the bug! I see zh-TW text in styles box.
![image](https://github.com/user-attachments/assets/440ed5fd-1b0a-4a98-9819-43878b4b49c5)

**Comment by timar** [comment]
In the zh-CN case the styles box is not the only issue. The sidebar is also partially localized.
![image](https://github.com/user-attachments/assets/935bc4e4-d93d-4ceb-af1f-dadb83817152)

**Comment by timar** [comment]
So, here is what I found: If we use `lang=zh-cn`, the problem occurs. LOKit is confused about this syntax. However, `lang=zh-CN` works just fine. I found similar issue with zh-tw vs. zh-TW. Note: zh-cn and zh-tw are not valid languagetags, zh-CN and zh-TW are.
info level log from LOKit (lang=zh-cn):
```
info:comphelper.lok:60291:60255:comphelper/source/misc/lok.cxx:68: Setting language from zxx to zh-cn
info:comphelper.lok:60291:60255:comphelper/source/misc/lok.cxx:68: Setting language from zh-CN to zh-cn
info:comphelper.lok:60291:60255:comphelper/source/misc/lok.cxx:68: Setting language from zh-CN to en-US
```
first it sets the language from "none" to zh-cn, and then differnt parts of code handled this wrong code differently, 3rd time en-US was selected.
info level log from LOKit (lang=zh-tw):
```
info:comphelper.lok:60892:60861:comphelper/source/misc/lok.cxx:68: Setting language from zxx to zh-tw
info:comphelper.lok:60892:60861:comphelper/source/misc/lok.cxx:68: Setting language from zh-TW to zh-tw
info:comphelper.lok:60892:60861:comphelper/source/misc/lok.cxx:68: Setting language from zh-TW to zh-CN
```
Actually I reproduced your mixed language case (I had to use incognito mode in browser and I was careful about the case of lang parameter).

So, probably it's a bug, that we can fix, but I wonder why you passed zh-cn and zh-tw, instead of zh-CN and zh-TW? In what environment did this problem occur? @pandagxnu ?
