### ISSUE TITLE
perf: de-prioritize rendering non-visible tiles 

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#9989]
In Kit.cpp (drainQueue) while we batch all the incoming input pieces first we then render all incoming tile requests.

      ```
  if (processInputEnabled() && !isLoadOngoing() &&
            !isBackgroundSaveProcess() && _queue->getTileQueueSize() > 0)
        {
            std::vector<TileCombined> tileRequests = _queue->popWholeTileQueue();

            // Put requests that include tiles in the visible area to the front to handle those first
            std::partition(tileRequests.begin(), tileRequests.end(), [this](const TileCombined& req) {
                return isTileRequestInsideVisibleArea(req); });
            for (auto& tileCombined : tileRequests)
                renderTiles(tileCombined);
     }
```

We should instead while there are events to process:

a) only render & send those that are inside a visible area and
b) re-spin the main-loop  and
c) only render non-visible tiles when there is nothing else to do =)

**Comment by sgothel** [comment]
@mmeeks is it OK for the invisible tiles requests to just vanish, i.e. being ignored iff the main-loop is busy (later on that)? 
In such case .. we just issue `renderTiles` on the `isTileRequestInsideVisibleArea` requests? 
(i.e. don't partition to favor visible tiles, but just for_all and send the visible tiles?)
Otherwise we would need to queue the pending invisible, but AFAIK this would be too much handling outdated data?

Need to check on the 'busy main-loop' criteria, i.e. `nothing else to do`

**Comment by mmeeks** [comment]
> @mmeeks is it OK for the invisible tiles requests to just vanish, i.e. being ignored iff the
> main-loop is busy (later on that)?

I would think c) above was quite clear on that. No it's not ok.

**Comment by sgothel** [comment]
> > @mmeeks is it OK for the invisible tiles requests to just vanish, i.e. being ignored iff the
> > main-loop is busy (later on that)?
> 
> I would think c) above was quite clear on that. No it's not ok.

Maybe a miswording, `vanish` is wrong. Paused until a better idle time as you wrote.
Will make a draft to discuss.
